// Code generated by ogen, DO NOT EDIT.

package sandboxapigen

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AttachSandboxExec implements attach-sandbox-exec operation.
	//
	// Opens a websocket carrying the framed bidirectional stream for a running sandbox exec. Input
	// frames write to exec stdin, output frames stream process output, and close-input frames close
	// stdin without detaching output.
	//
	// GET /api/projects/{projectId}/sandboxes/{sandboxId}/execs/{execId}/attach
	AttachSandboxExec(ctx context.Context, params AttachSandboxExecParams) (*AttachSandboxExecSwitchingProtocols, error)
	// CreateSandboxExec implements create-sandbox-exec operation.
	//
	// Create an exec runtime in a sandbox.
	//
	// POST /api/projects/{projectId}/sandboxes/{sandboxId}/execs
	CreateSandboxExec(ctx context.Context, req *CreateSandboxExecRequest, params CreateSandboxExecParams) (*CreateSandboxExecResponse, error)
	// DeleteSandboxExec implements delete-sandbox-exec operation.
	//
	// Destroy an exec runtime in a sandbox.
	//
	// DELETE /api/projects/{projectId}/sandboxes/{sandboxId}/execs/{execId}
	DeleteSandboxExec(ctx context.Context, params DeleteSandboxExecParams) error
	// GetSandboxExec implements get-sandbox-exec operation.
	//
	// Get an exec runtime in a sandbox.
	//
	// GET /api/projects/{projectId}/sandboxes/{sandboxId}/execs/{execId}
	GetSandboxExec(ctx context.Context, params GetSandboxExecParams) (*SandboxExec, error)
	// GetSandboxExecResources implements get-sandbox-exec-resources operation.
	//
	// Get the latest opaque resource snapshot for a sandbox exec.
	//
	// GET /api/projects/{projectId}/sandboxes/{sandboxId}/execs/{execId}/resources
	GetSandboxExecResources(ctx context.Context, params GetSandboxExecResourcesParams) (*ResourceSnapshot, error)
	// ListAgentHooks implements list-agent-hooks operation.
	//
	// List recent sandbox agent hook payload logs.
	//
	// GET /api/projects/{projectId}/sandboxes/{sandboxId}/agent-hooks
	ListAgentHooks(ctx context.Context, params ListAgentHooksParams) (*AgentHookLogsResponse, error)
	// ListSandboxExecEvents implements list-sandbox-exec-events operation.
	//
	// List recent audit events for a sandbox exec.
	//
	// GET /api/projects/{projectId}/sandboxes/{sandboxId}/execs/{execId}/events
	ListSandboxExecEvents(ctx context.Context, params ListSandboxExecEventsParams) (*SandboxExecEventsResponse, error)
	// ListSandboxExecLogs implements list-sandbox-exec-logs operation.
	//
	// List logs for a sandbox exec.
	//
	// GET /api/projects/{projectId}/sandboxes/{sandboxId}/execs/{execId}/logs
	ListSandboxExecLogs(ctx context.Context, params ListSandboxExecLogsParams) (*SandboxExecLogsResponse, error)
	// ListSandboxExecResourceHistory implements list-sandbox-exec-resource-history operation.
	//
	// List recent opaque resource snapshots for a sandbox exec.
	//
	// GET /api/projects/{projectId}/sandboxes/{sandboxId}/execs/{execId}/resources/history
	ListSandboxExecResourceHistory(ctx context.Context, params ListSandboxExecResourceHistoryParams) (*ResourceHistoryResponse, error)
	// ListSandboxExecs implements list-sandbox-execs operation.
	//
	// List exec runtimes in a sandbox.
	//
	// GET /api/projects/{projectId}/sandboxes/{sandboxId}/execs
	ListSandboxExecs(ctx context.Context, params ListSandboxExecsParams) (*SandboxExecsResponse, error)
	// StartSandboxExec implements start-sandbox-exec operation.
	//
	// Starts a prepared sandbox exec after any desired attach stream has connected.
	//
	// POST /api/projects/{projectId}/sandboxes/{sandboxId}/execs/{execId}/start
	StartSandboxExec(ctx context.Context, params StartSandboxExecParams) (*SandboxExec, error)
	// StreamSandboxExecResources implements stream-sandbox-exec-resources operation.
	//
	// Stream opaque resource snapshots for a sandbox exec.
	//
	// GET /api/projects/{projectId}/sandboxes/{sandboxId}/execs/{execId}/resources/stream
	StreamSandboxExecResources(ctx context.Context, params StreamSandboxExecResourcesParams) (StreamSandboxExecResourcesOK, error)
	// NewError creates *ErrorResponseStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorResponseStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
