// Code generated by ogen, DO NOT EDIT.

package sandboxapigen

import (
	"fmt"
	"io"
	"time"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
)

func (s *ErrorResponseStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/AgentHookLog
type AgentHookLog struct {
	CreatedAt time.Time `json:"createdAt"`
	// Provider-specific hook event name.
	Event string `json:"event"`
	// Hook log ID.
	ID string `json:"id"`
	// Raw provider hook payload.
	Payload jx.Raw `json:"payload"`
	// Agent hook provider.
	Provider string `json:"provider"`
	// Agent terminal runtime ID that emitted the hook.
	TerminalId OptString `json:"terminalId"`
}

// GetCreatedAt returns the value of CreatedAt.
func (s *AgentHookLog) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetEvent returns the value of Event.
func (s *AgentHookLog) GetEvent() string {
	return s.Event
}

// GetID returns the value of ID.
func (s *AgentHookLog) GetID() string {
	return s.ID
}

// GetPayload returns the value of Payload.
func (s *AgentHookLog) GetPayload() jx.Raw {
	return s.Payload
}

// GetProvider returns the value of Provider.
func (s *AgentHookLog) GetProvider() string {
	return s.Provider
}

// GetTerminalId returns the value of TerminalId.
func (s *AgentHookLog) GetTerminalId() OptString {
	return s.TerminalId
}

// SetCreatedAt sets the value of CreatedAt.
func (s *AgentHookLog) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetEvent sets the value of Event.
func (s *AgentHookLog) SetEvent(val string) {
	s.Event = val
}

// SetID sets the value of ID.
func (s *AgentHookLog) SetID(val string) {
	s.ID = val
}

// SetPayload sets the value of Payload.
func (s *AgentHookLog) SetPayload(val jx.Raw) {
	s.Payload = val
}

// SetProvider sets the value of Provider.
func (s *AgentHookLog) SetProvider(val string) {
	s.Provider = val
}

// SetTerminalId sets the value of TerminalId.
func (s *AgentHookLog) SetTerminalId(val OptString) {
	s.TerminalId = val
}

// Ref: #/components/schemas/AgentHookLogsResponse
type AgentHookLogsResponse struct {
	Hooks []AgentHookLog `json:"hooks"`
}

// GetHooks returns the value of Hooks.
func (s *AgentHookLogsResponse) GetHooks() []AgentHookLog {
	return s.Hooks
}

// SetHooks sets the value of Hooks.
func (s *AgentHookLogsResponse) SetHooks(val []AgentHookLog) {
	s.Hooks = val
}

// Ref: #/components/schemas/AgentTerminal
type AgentTerminal struct {
	// Coding agent CLI selected for the terminal.
	AgentId OptString `json:"agentId"`
	// Command used to launch the coding-agent CLI.
	Command   []string  `json:"command"`
	CreatedAt time.Time `json:"createdAt"`
	// Runtime error detail when the terminal failed.
	Error OptString `json:"error"`
	// Process exit code when the terminal has exited.
	ExitCode OptInt64    `json:"exitCode"`
	ExitedAt OptDateTime `json:"exitedAt"`
	// Agent terminal runtime ID.
	ID string `json:"id"`
	// Sandbox-agent-owned terminal metadata.
	Metadata OptAgentTerminalMetadata `json:"metadata"`
	// Sandbox-local process ID when known.
	Pid OptInt64 `json:"pid"`
	// Whether this is the sandbox's primary terminal, launched by the sandbox-agent from the sandbox
	// prompt. Set only by the sandbox-agent; it cannot be requested through terminal create.
	Primary   OptBool     `json:"primary"`
	StartedAt OptDateTime `json:"startedAt"`
	// Current observed terminal runtime status.
	Status AgentTerminalStatus `json:"status"`
	// Systemd unit or scope name when known.
	Unit OptString `json:"unit"`
	// Working directory for the terminal process.
	Workdir string `json:"workdir"`
}

// GetAgentId returns the value of AgentId.
func (s *AgentTerminal) GetAgentId() OptString {
	return s.AgentId
}

// GetCommand returns the value of Command.
func (s *AgentTerminal) GetCommand() []string {
	return s.Command
}

// GetCreatedAt returns the value of CreatedAt.
func (s *AgentTerminal) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetError returns the value of Error.
func (s *AgentTerminal) GetError() OptString {
	return s.Error
}

// GetExitCode returns the value of ExitCode.
func (s *AgentTerminal) GetExitCode() OptInt64 {
	return s.ExitCode
}

// GetExitedAt returns the value of ExitedAt.
func (s *AgentTerminal) GetExitedAt() OptDateTime {
	return s.ExitedAt
}

// GetID returns the value of ID.
func (s *AgentTerminal) GetID() string {
	return s.ID
}

// GetMetadata returns the value of Metadata.
func (s *AgentTerminal) GetMetadata() OptAgentTerminalMetadata {
	return s.Metadata
}

// GetPid returns the value of Pid.
func (s *AgentTerminal) GetPid() OptInt64 {
	return s.Pid
}

// GetPrimary returns the value of Primary.
func (s *AgentTerminal) GetPrimary() OptBool {
	return s.Primary
}

// GetStartedAt returns the value of StartedAt.
func (s *AgentTerminal) GetStartedAt() OptDateTime {
	return s.StartedAt
}

// GetStatus returns the value of Status.
func (s *AgentTerminal) GetStatus() AgentTerminalStatus {
	return s.Status
}

// GetUnit returns the value of Unit.
func (s *AgentTerminal) GetUnit() OptString {
	return s.Unit
}

// GetWorkdir returns the value of Workdir.
func (s *AgentTerminal) GetWorkdir() string {
	return s.Workdir
}

// SetAgentId sets the value of AgentId.
func (s *AgentTerminal) SetAgentId(val OptString) {
	s.AgentId = val
}

// SetCommand sets the value of Command.
func (s *AgentTerminal) SetCommand(val []string) {
	s.Command = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *AgentTerminal) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetError sets the value of Error.
func (s *AgentTerminal) SetError(val OptString) {
	s.Error = val
}

// SetExitCode sets the value of ExitCode.
func (s *AgentTerminal) SetExitCode(val OptInt64) {
	s.ExitCode = val
}

// SetExitedAt sets the value of ExitedAt.
func (s *AgentTerminal) SetExitedAt(val OptDateTime) {
	s.ExitedAt = val
}

// SetID sets the value of ID.
func (s *AgentTerminal) SetID(val string) {
	s.ID = val
}

// SetMetadata sets the value of Metadata.
func (s *AgentTerminal) SetMetadata(val OptAgentTerminalMetadata) {
	s.Metadata = val
}

// SetPid sets the value of Pid.
func (s *AgentTerminal) SetPid(val OptInt64) {
	s.Pid = val
}

// SetPrimary sets the value of Primary.
func (s *AgentTerminal) SetPrimary(val OptBool) {
	s.Primary = val
}

// SetStartedAt sets the value of StartedAt.
func (s *AgentTerminal) SetStartedAt(val OptDateTime) {
	s.StartedAt = val
}

// SetStatus sets the value of Status.
func (s *AgentTerminal) SetStatus(val AgentTerminalStatus) {
	s.Status = val
}

// SetUnit sets the value of Unit.
func (s *AgentTerminal) SetUnit(val OptString) {
	s.Unit = val
}

// SetWorkdir sets the value of Workdir.
func (s *AgentTerminal) SetWorkdir(val string) {
	s.Workdir = val
}

// Ref: #/components/schemas/AgentTerminalEvent
type AgentTerminalEvent struct {
	CreatedAt time.Time `json:"createdAt"`
	// Opaque event details.
	Details jx.Raw `json:"details"`
	// Event ID.
	ID string `json:"id"`
	// Human-readable event message.
	Message OptString `json:"message"`
	// Agent terminal runtime ID.
	TerminalId OptString `json:"terminalId"`
	// Event type.
	Type string `json:"type"`
}

// GetCreatedAt returns the value of CreatedAt.
func (s *AgentTerminalEvent) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetDetails returns the value of Details.
func (s *AgentTerminalEvent) GetDetails() jx.Raw {
	return s.Details
}

// GetID returns the value of ID.
func (s *AgentTerminalEvent) GetID() string {
	return s.ID
}

// GetMessage returns the value of Message.
func (s *AgentTerminalEvent) GetMessage() OptString {
	return s.Message
}

// GetTerminalId returns the value of TerminalId.
func (s *AgentTerminalEvent) GetTerminalId() OptString {
	return s.TerminalId
}

// GetType returns the value of Type.
func (s *AgentTerminalEvent) GetType() string {
	return s.Type
}

// SetCreatedAt sets the value of CreatedAt.
func (s *AgentTerminalEvent) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetDetails sets the value of Details.
func (s *AgentTerminalEvent) SetDetails(val jx.Raw) {
	s.Details = val
}

// SetID sets the value of ID.
func (s *AgentTerminalEvent) SetID(val string) {
	s.ID = val
}

// SetMessage sets the value of Message.
func (s *AgentTerminalEvent) SetMessage(val OptString) {
	s.Message = val
}

// SetTerminalId sets the value of TerminalId.
func (s *AgentTerminalEvent) SetTerminalId(val OptString) {
	s.TerminalId = val
}

// SetType sets the value of Type.
func (s *AgentTerminalEvent) SetType(val string) {
	s.Type = val
}

// Ref: #/components/schemas/AgentTerminalEventsResponse
type AgentTerminalEventsResponse struct {
	Events []AgentTerminalEvent `json:"events"`
}

// GetEvents returns the value of Events.
func (s *AgentTerminalEventsResponse) GetEvents() []AgentTerminalEvent {
	return s.Events
}

// SetEvents sets the value of Events.
func (s *AgentTerminalEventsResponse) SetEvents(val []AgentTerminalEvent) {
	s.Events = val
}

// Ref: #/components/schemas/AgentTerminalLogEntry
type AgentTerminalLogEntry struct {
	// Base64-encoded raw PTY bytes.
	Data []byte `json:"data"`
	// PTY direction for this chunk.
	Stream AgentTerminalLogEntryStream `json:"stream"`
	// Time this PTY input or output chunk was observed.
	Timestamp time.Time `json:"timestamp"`
}

// GetData returns the value of Data.
func (s *AgentTerminalLogEntry) GetData() []byte {
	return s.Data
}

// GetStream returns the value of Stream.
func (s *AgentTerminalLogEntry) GetStream() AgentTerminalLogEntryStream {
	return s.Stream
}

// GetTimestamp returns the value of Timestamp.
func (s *AgentTerminalLogEntry) GetTimestamp() time.Time {
	return s.Timestamp
}

// SetData sets the value of Data.
func (s *AgentTerminalLogEntry) SetData(val []byte) {
	s.Data = val
}

// SetStream sets the value of Stream.
func (s *AgentTerminalLogEntry) SetStream(val AgentTerminalLogEntryStream) {
	s.Stream = val
}

// SetTimestamp sets the value of Timestamp.
func (s *AgentTerminalLogEntry) SetTimestamp(val time.Time) {
	s.Timestamp = val
}

// PTY direction for this chunk.
type AgentTerminalLogEntryStream string

const (
	AgentTerminalLogEntryStreamInput  AgentTerminalLogEntryStream = "input"
	AgentTerminalLogEntryStreamOutput AgentTerminalLogEntryStream = "output"
)

// AllValues returns all AgentTerminalLogEntryStream values.
func (AgentTerminalLogEntryStream) AllValues() []AgentTerminalLogEntryStream {
	return []AgentTerminalLogEntryStream{
		AgentTerminalLogEntryStreamInput,
		AgentTerminalLogEntryStreamOutput,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AgentTerminalLogEntryStream) MarshalText() ([]byte, error) {
	switch s {
	case AgentTerminalLogEntryStreamInput:
		return []byte(s), nil
	case AgentTerminalLogEntryStreamOutput:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *AgentTerminalLogEntryStream) UnmarshalText(data []byte) error {
	switch AgentTerminalLogEntryStream(data) {
	case AgentTerminalLogEntryStreamInput:
		*s = AgentTerminalLogEntryStreamInput
		return nil
	case AgentTerminalLogEntryStreamOutput:
		*s = AgentTerminalLogEntryStreamOutput
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/AgentTerminalLogsResponse
type AgentTerminalLogsResponse struct {
	Entries []AgentTerminalLogEntry `json:"entries"`
}

// GetEntries returns the value of Entries.
func (s *AgentTerminalLogsResponse) GetEntries() []AgentTerminalLogEntry {
	return s.Entries
}

// SetEntries sets the value of Entries.
func (s *AgentTerminalLogsResponse) SetEntries(val []AgentTerminalLogEntry) {
	s.Entries = val
}

// Sandbox-agent-owned terminal metadata.
type AgentTerminalMetadata map[string]string

func (s *AgentTerminalMetadata) init() AgentTerminalMetadata {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

// Current observed terminal runtime status.
type AgentTerminalStatus string

const (
	AgentTerminalStatusStarting AgentTerminalStatus = "starting"
	AgentTerminalStatusRunning  AgentTerminalStatus = "running"
	AgentTerminalStatusExited   AgentTerminalStatus = "exited"
	AgentTerminalStatusFailed   AgentTerminalStatus = "failed"
	AgentTerminalStatusLost     AgentTerminalStatus = "lost"
)

// AllValues returns all AgentTerminalStatus values.
func (AgentTerminalStatus) AllValues() []AgentTerminalStatus {
	return []AgentTerminalStatus{
		AgentTerminalStatusStarting,
		AgentTerminalStatusRunning,
		AgentTerminalStatusExited,
		AgentTerminalStatusFailed,
		AgentTerminalStatusLost,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AgentTerminalStatus) MarshalText() ([]byte, error) {
	switch s {
	case AgentTerminalStatusStarting:
		return []byte(s), nil
	case AgentTerminalStatusRunning:
		return []byte(s), nil
	case AgentTerminalStatusExited:
		return []byte(s), nil
	case AgentTerminalStatusFailed:
		return []byte(s), nil
	case AgentTerminalStatusLost:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *AgentTerminalStatus) UnmarshalText(data []byte) error {
	switch AgentTerminalStatus(data) {
	case AgentTerminalStatusStarting:
		*s = AgentTerminalStatusStarting
		return nil
	case AgentTerminalStatusRunning:
		*s = AgentTerminalStatusRunning
		return nil
	case AgentTerminalStatusExited:
		*s = AgentTerminalStatusExited
		return nil
	case AgentTerminalStatusFailed:
		*s = AgentTerminalStatusFailed
		return nil
	case AgentTerminalStatusLost:
		*s = AgentTerminalStatusLost
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/AgentTerminalsResponse
type AgentTerminalsResponse struct {
	Terminals []AgentTerminal `json:"terminals"`
}

// GetTerminals returns the value of Terminals.
func (s *AgentTerminalsResponse) GetTerminals() []AgentTerminal {
	return s.Terminals
}

// SetTerminals sets the value of Terminals.
func (s *AgentTerminalsResponse) SetTerminals(val []AgentTerminal) {
	s.Terminals = val
}

// AttachAgentTerminalSwitchingProtocols is response for AttachAgentTerminal operation.
type AttachAgentTerminalSwitchingProtocols struct {
	Connection OptString
	Upgrade    OptString
}

// GetConnection returns the value of Connection.
func (s *AttachAgentTerminalSwitchingProtocols) GetConnection() OptString {
	return s.Connection
}

// GetUpgrade returns the value of Upgrade.
func (s *AttachAgentTerminalSwitchingProtocols) GetUpgrade() OptString {
	return s.Upgrade
}

// SetConnection sets the value of Connection.
func (s *AttachAgentTerminalSwitchingProtocols) SetConnection(val OptString) {
	s.Connection = val
}

// SetUpgrade sets the value of Upgrade.
func (s *AttachAgentTerminalSwitchingProtocols) SetUpgrade(val OptString) {
	s.Upgrade = val
}

// AttachSandboxExecSwitchingProtocols is response for AttachSandboxExec operation.
type AttachSandboxExecSwitchingProtocols struct {
	Connection OptString
	Upgrade    OptString
}

// GetConnection returns the value of Connection.
func (s *AttachSandboxExecSwitchingProtocols) GetConnection() OptString {
	return s.Connection
}

// GetUpgrade returns the value of Upgrade.
func (s *AttachSandboxExecSwitchingProtocols) GetUpgrade() OptString {
	return s.Upgrade
}

// SetConnection sets the value of Connection.
func (s *AttachSandboxExecSwitchingProtocols) SetConnection(val OptString) {
	s.Connection = val
}

// SetUpgrade sets the value of Upgrade.
func (s *AttachSandboxExecSwitchingProtocols) SetUpgrade(val OptString) {
	s.Upgrade = val
}

// Ref: #/components/schemas/CreateAgentTerminalRequest
type CreateAgentTerminalRequest struct {
	// Coding agent CLI to start. Defaults to the sandbox configured agent when omitted.
	AgentId OptString `json:"agentId"`
	// Additional command arguments for the coding-agent CLI.
	Args []string `json:"args"`
	// Initial PTY columns when a PTY is allocated.
	Cols OptInt `json:"cols"`
	// Additional environment variables for the terminal process.
	Env OptCreateAgentTerminalRequestEnv `json:"env"`
	// Caller-supplied metadata to associate with the terminal.
	Metadata OptCreateAgentTerminalRequestMetadata `json:"metadata"`
	// Initial PTY rows when a PTY is allocated.
	Rows OptInt `json:"rows"`
	// Working directory for the terminal process.
	Workdir OptString `json:"workdir"`
}

// GetAgentId returns the value of AgentId.
func (s *CreateAgentTerminalRequest) GetAgentId() OptString {
	return s.AgentId
}

// GetArgs returns the value of Args.
func (s *CreateAgentTerminalRequest) GetArgs() []string {
	return s.Args
}

// GetCols returns the value of Cols.
func (s *CreateAgentTerminalRequest) GetCols() OptInt {
	return s.Cols
}

// GetEnv returns the value of Env.
func (s *CreateAgentTerminalRequest) GetEnv() OptCreateAgentTerminalRequestEnv {
	return s.Env
}

// GetMetadata returns the value of Metadata.
func (s *CreateAgentTerminalRequest) GetMetadata() OptCreateAgentTerminalRequestMetadata {
	return s.Metadata
}

// GetRows returns the value of Rows.
func (s *CreateAgentTerminalRequest) GetRows() OptInt {
	return s.Rows
}

// GetWorkdir returns the value of Workdir.
func (s *CreateAgentTerminalRequest) GetWorkdir() OptString {
	return s.Workdir
}

// SetAgentId sets the value of AgentId.
func (s *CreateAgentTerminalRequest) SetAgentId(val OptString) {
	s.AgentId = val
}

// SetArgs sets the value of Args.
func (s *CreateAgentTerminalRequest) SetArgs(val []string) {
	s.Args = val
}

// SetCols sets the value of Cols.
func (s *CreateAgentTerminalRequest) SetCols(val OptInt) {
	s.Cols = val
}

// SetEnv sets the value of Env.
func (s *CreateAgentTerminalRequest) SetEnv(val OptCreateAgentTerminalRequestEnv) {
	s.Env = val
}

// SetMetadata sets the value of Metadata.
func (s *CreateAgentTerminalRequest) SetMetadata(val OptCreateAgentTerminalRequestMetadata) {
	s.Metadata = val
}

// SetRows sets the value of Rows.
func (s *CreateAgentTerminalRequest) SetRows(val OptInt) {
	s.Rows = val
}

// SetWorkdir sets the value of Workdir.
func (s *CreateAgentTerminalRequest) SetWorkdir(val OptString) {
	s.Workdir = val
}

// Additional environment variables for the terminal process.
type CreateAgentTerminalRequestEnv map[string]string

func (s *CreateAgentTerminalRequestEnv) init() CreateAgentTerminalRequestEnv {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

// Caller-supplied metadata to associate with the terminal.
type CreateAgentTerminalRequestMetadata map[string]string

func (s *CreateAgentTerminalRequestMetadata) init() CreateAgentTerminalRequestMetadata {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/CreateAgentTerminalResponse
type CreateAgentTerminalResponse struct {
	Terminal AgentTerminal `json:"terminal"`
}

// GetTerminal returns the value of Terminal.
func (s *CreateAgentTerminalResponse) GetTerminal() AgentTerminal {
	return s.Terminal
}

// SetTerminal sets the value of Terminal.
func (s *CreateAgentTerminalResponse) SetTerminal(val AgentTerminal) {
	s.Terminal = val
}

func (*CreateAgentTerminalResponse) createAgentTerminalRes() {}

// CreateAgentTerminalSwitchingProtocols is response for CreateAgentTerminal operation.
type CreateAgentTerminalSwitchingProtocols struct {
	Connection OptString
	Upgrade    OptString
}

// GetConnection returns the value of Connection.
func (s *CreateAgentTerminalSwitchingProtocols) GetConnection() OptString {
	return s.Connection
}

// GetUpgrade returns the value of Upgrade.
func (s *CreateAgentTerminalSwitchingProtocols) GetUpgrade() OptString {
	return s.Upgrade
}

// SetConnection sets the value of Connection.
func (s *CreateAgentTerminalSwitchingProtocols) SetConnection(val OptString) {
	s.Connection = val
}

// SetUpgrade sets the value of Upgrade.
func (s *CreateAgentTerminalSwitchingProtocols) SetUpgrade(val OptString) {
	s.Upgrade = val
}

func (*CreateAgentTerminalSwitchingProtocols) createAgentTerminalRes() {}

// Ref: #/components/schemas/CreateSandboxExecRequest
type CreateSandboxExecRequest struct {
	// Initial PTY columns when a PTY is allocated.
	Cols OptInt `json:"cols"`
	// Command argv to execute in the sandbox.
	Command []string `json:"command"`
	// Additional environment variables for the exec process.
	Env OptCreateSandboxExecRequestEnv `json:"env"`
	// Caller-supplied metadata to associate with the exec.
	Metadata OptCreateSandboxExecRequestMetadata `json:"metadata"`
	// Initial PTY rows when a PTY is allocated.
	Rows OptInt `json:"rows"`
	// Allocate a PTY for the exec process.
	Tty OptBool `json:"tty"`
	// User identity used to run the exec process.
	User OptSandboxUser `json:"user"`
	// Working directory for the exec process.
	Workdir OptString `json:"workdir"`
}

// GetCols returns the value of Cols.
func (s *CreateSandboxExecRequest) GetCols() OptInt {
	return s.Cols
}

// GetCommand returns the value of Command.
func (s *CreateSandboxExecRequest) GetCommand() []string {
	return s.Command
}

// GetEnv returns the value of Env.
func (s *CreateSandboxExecRequest) GetEnv() OptCreateSandboxExecRequestEnv {
	return s.Env
}

// GetMetadata returns the value of Metadata.
func (s *CreateSandboxExecRequest) GetMetadata() OptCreateSandboxExecRequestMetadata {
	return s.Metadata
}

// GetRows returns the value of Rows.
func (s *CreateSandboxExecRequest) GetRows() OptInt {
	return s.Rows
}

// GetTty returns the value of Tty.
func (s *CreateSandboxExecRequest) GetTty() OptBool {
	return s.Tty
}

// GetUser returns the value of User.
func (s *CreateSandboxExecRequest) GetUser() OptSandboxUser {
	return s.User
}

// GetWorkdir returns the value of Workdir.
func (s *CreateSandboxExecRequest) GetWorkdir() OptString {
	return s.Workdir
}

// SetCols sets the value of Cols.
func (s *CreateSandboxExecRequest) SetCols(val OptInt) {
	s.Cols = val
}

// SetCommand sets the value of Command.
func (s *CreateSandboxExecRequest) SetCommand(val []string) {
	s.Command = val
}

// SetEnv sets the value of Env.
func (s *CreateSandboxExecRequest) SetEnv(val OptCreateSandboxExecRequestEnv) {
	s.Env = val
}

// SetMetadata sets the value of Metadata.
func (s *CreateSandboxExecRequest) SetMetadata(val OptCreateSandboxExecRequestMetadata) {
	s.Metadata = val
}

// SetRows sets the value of Rows.
func (s *CreateSandboxExecRequest) SetRows(val OptInt) {
	s.Rows = val
}

// SetTty sets the value of Tty.
func (s *CreateSandboxExecRequest) SetTty(val OptBool) {
	s.Tty = val
}

// SetUser sets the value of User.
func (s *CreateSandboxExecRequest) SetUser(val OptSandboxUser) {
	s.User = val
}

// SetWorkdir sets the value of Workdir.
func (s *CreateSandboxExecRequest) SetWorkdir(val OptString) {
	s.Workdir = val
}

// Additional environment variables for the exec process.
type CreateSandboxExecRequestEnv map[string]string

func (s *CreateSandboxExecRequestEnv) init() CreateSandboxExecRequestEnv {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

// Caller-supplied metadata to associate with the exec.
type CreateSandboxExecRequestMetadata map[string]string

func (s *CreateSandboxExecRequestMetadata) init() CreateSandboxExecRequestMetadata {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/CreateSandboxExecResponse
type CreateSandboxExecResponse struct {
	Exec SandboxExec `json:"exec"`
}

// GetExec returns the value of Exec.
func (s *CreateSandboxExecResponse) GetExec() SandboxExec {
	return s.Exec
}

// SetExec sets the value of Exec.
func (s *CreateSandboxExecResponse) SetExec(val SandboxExec) {
	s.Exec = val
}

// DeleteAgentTerminalNoContent is response for DeleteAgentTerminal operation.
type DeleteAgentTerminalNoContent struct{}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	// Human-readable error message.
	Error string `json:"error"`
}

// GetError returns the value of Error.
func (s *ErrorResponse) GetError() string {
	return s.Error
}

// SetError sets the value of Error.
func (s *ErrorResponse) SetError(val string) {
	s.Error = val
}

// ErrorResponseStatusCode wraps ErrorResponse with StatusCode.
type ErrorResponseStatusCode struct {
	StatusCode int
	Response   ErrorResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorResponseStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorResponseStatusCode) GetResponse() ErrorResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorResponseStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorResponseStatusCode) SetResponse(val ErrorResponse) {
	s.Response = val
}

// NewOptAgentTerminalMetadata returns new OptAgentTerminalMetadata with value set to v.
func NewOptAgentTerminalMetadata(v AgentTerminalMetadata) OptAgentTerminalMetadata {
	return OptAgentTerminalMetadata{
		Value: v,
		Set:   true,
	}
}

// OptAgentTerminalMetadata is optional AgentTerminalMetadata.
type OptAgentTerminalMetadata struct {
	Value AgentTerminalMetadata
	Set   bool
}

// IsSet returns true if OptAgentTerminalMetadata was set.
func (o OptAgentTerminalMetadata) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAgentTerminalMetadata) Reset() {
	var v AgentTerminalMetadata
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAgentTerminalMetadata) SetTo(v AgentTerminalMetadata) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAgentTerminalMetadata) Get() (v AgentTerminalMetadata, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAgentTerminalMetadata) Or(d AgentTerminalMetadata) AgentTerminalMetadata {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateAgentTerminalRequestEnv returns new OptCreateAgentTerminalRequestEnv with value set to v.
func NewOptCreateAgentTerminalRequestEnv(v CreateAgentTerminalRequestEnv) OptCreateAgentTerminalRequestEnv {
	return OptCreateAgentTerminalRequestEnv{
		Value: v,
		Set:   true,
	}
}

// OptCreateAgentTerminalRequestEnv is optional CreateAgentTerminalRequestEnv.
type OptCreateAgentTerminalRequestEnv struct {
	Value CreateAgentTerminalRequestEnv
	Set   bool
}

// IsSet returns true if OptCreateAgentTerminalRequestEnv was set.
func (o OptCreateAgentTerminalRequestEnv) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateAgentTerminalRequestEnv) Reset() {
	var v CreateAgentTerminalRequestEnv
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateAgentTerminalRequestEnv) SetTo(v CreateAgentTerminalRequestEnv) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateAgentTerminalRequestEnv) Get() (v CreateAgentTerminalRequestEnv, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateAgentTerminalRequestEnv) Or(d CreateAgentTerminalRequestEnv) CreateAgentTerminalRequestEnv {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateAgentTerminalRequestMetadata returns new OptCreateAgentTerminalRequestMetadata with value set to v.
func NewOptCreateAgentTerminalRequestMetadata(v CreateAgentTerminalRequestMetadata) OptCreateAgentTerminalRequestMetadata {
	return OptCreateAgentTerminalRequestMetadata{
		Value: v,
		Set:   true,
	}
}

// OptCreateAgentTerminalRequestMetadata is optional CreateAgentTerminalRequestMetadata.
type OptCreateAgentTerminalRequestMetadata struct {
	Value CreateAgentTerminalRequestMetadata
	Set   bool
}

// IsSet returns true if OptCreateAgentTerminalRequestMetadata was set.
func (o OptCreateAgentTerminalRequestMetadata) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateAgentTerminalRequestMetadata) Reset() {
	var v CreateAgentTerminalRequestMetadata
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateAgentTerminalRequestMetadata) SetTo(v CreateAgentTerminalRequestMetadata) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateAgentTerminalRequestMetadata) Get() (v CreateAgentTerminalRequestMetadata, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateAgentTerminalRequestMetadata) Or(d CreateAgentTerminalRequestMetadata) CreateAgentTerminalRequestMetadata {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateSandboxExecRequestEnv returns new OptCreateSandboxExecRequestEnv with value set to v.
func NewOptCreateSandboxExecRequestEnv(v CreateSandboxExecRequestEnv) OptCreateSandboxExecRequestEnv {
	return OptCreateSandboxExecRequestEnv{
		Value: v,
		Set:   true,
	}
}

// OptCreateSandboxExecRequestEnv is optional CreateSandboxExecRequestEnv.
type OptCreateSandboxExecRequestEnv struct {
	Value CreateSandboxExecRequestEnv
	Set   bool
}

// IsSet returns true if OptCreateSandboxExecRequestEnv was set.
func (o OptCreateSandboxExecRequestEnv) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateSandboxExecRequestEnv) Reset() {
	var v CreateSandboxExecRequestEnv
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateSandboxExecRequestEnv) SetTo(v CreateSandboxExecRequestEnv) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateSandboxExecRequestEnv) Get() (v CreateSandboxExecRequestEnv, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateSandboxExecRequestEnv) Or(d CreateSandboxExecRequestEnv) CreateSandboxExecRequestEnv {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateSandboxExecRequestMetadata returns new OptCreateSandboxExecRequestMetadata with value set to v.
func NewOptCreateSandboxExecRequestMetadata(v CreateSandboxExecRequestMetadata) OptCreateSandboxExecRequestMetadata {
	return OptCreateSandboxExecRequestMetadata{
		Value: v,
		Set:   true,
	}
}

// OptCreateSandboxExecRequestMetadata is optional CreateSandboxExecRequestMetadata.
type OptCreateSandboxExecRequestMetadata struct {
	Value CreateSandboxExecRequestMetadata
	Set   bool
}

// IsSet returns true if OptCreateSandboxExecRequestMetadata was set.
func (o OptCreateSandboxExecRequestMetadata) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateSandboxExecRequestMetadata) Reset() {
	var v CreateSandboxExecRequestMetadata
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateSandboxExecRequestMetadata) SetTo(v CreateSandboxExecRequestMetadata) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateSandboxExecRequestMetadata) Get() (v CreateSandboxExecRequestMetadata, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateSandboxExecRequestMetadata) Or(d CreateSandboxExecRequestMetadata) CreateSandboxExecRequestMetadata {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSandboxExecEnv returns new OptSandboxExecEnv with value set to v.
func NewOptSandboxExecEnv(v SandboxExecEnv) OptSandboxExecEnv {
	return OptSandboxExecEnv{
		Value: v,
		Set:   true,
	}
}

// OptSandboxExecEnv is optional SandboxExecEnv.
type OptSandboxExecEnv struct {
	Value SandboxExecEnv
	Set   bool
}

// IsSet returns true if OptSandboxExecEnv was set.
func (o OptSandboxExecEnv) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSandboxExecEnv) Reset() {
	var v SandboxExecEnv
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSandboxExecEnv) SetTo(v SandboxExecEnv) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSandboxExecEnv) Get() (v SandboxExecEnv, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSandboxExecEnv) Or(d SandboxExecEnv) SandboxExecEnv {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSandboxExecMetadata returns new OptSandboxExecMetadata with value set to v.
func NewOptSandboxExecMetadata(v SandboxExecMetadata) OptSandboxExecMetadata {
	return OptSandboxExecMetadata{
		Value: v,
		Set:   true,
	}
}

// OptSandboxExecMetadata is optional SandboxExecMetadata.
type OptSandboxExecMetadata struct {
	Value SandboxExecMetadata
	Set   bool
}

// IsSet returns true if OptSandboxExecMetadata was set.
func (o OptSandboxExecMetadata) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSandboxExecMetadata) Reset() {
	var v SandboxExecMetadata
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSandboxExecMetadata) SetTo(v SandboxExecMetadata) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSandboxExecMetadata) Get() (v SandboxExecMetadata, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSandboxExecMetadata) Or(d SandboxExecMetadata) SandboxExecMetadata {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSandboxUser returns new OptSandboxUser with value set to v.
func NewOptSandboxUser(v SandboxUser) OptSandboxUser {
	return OptSandboxUser{
		Value: v,
		Set:   true,
	}
}

// OptSandboxUser is optional SandboxUser.
type OptSandboxUser struct {
	Value SandboxUser
	Set   bool
}

// IsSet returns true if OptSandboxUser was set.
func (o OptSandboxUser) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSandboxUser) Reset() {
	var v SandboxUser
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSandboxUser) SetTo(v SandboxUser) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSandboxUser) Get() (v SandboxUser, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSandboxUser) Or(d SandboxUser) SandboxUser {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/ResourceHistoryResponse
type ResourceHistoryResponse struct {
	Snapshots []ResourceSnapshot `json:"snapshots"`
}

// GetSnapshots returns the value of Snapshots.
func (s *ResourceHistoryResponse) GetSnapshots() []ResourceSnapshot {
	return s.Snapshots
}

// SetSnapshots sets the value of Snapshots.
func (s *ResourceHistoryResponse) SetSnapshots(val []ResourceSnapshot) {
	s.Snapshots = val
}

// Ref: #/components/schemas/ResourceSnapshot
type ResourceSnapshot struct {
	// Opaque OS, cgroup, systemd, and process resource dump.
	Data jx.Raw `json:"data"`
	// Time when the snapshot was collected.
	SampledAt time.Time `json:"sampledAt"`
	// Resource collector source.
	Source string `json:"source"`
	// Agent terminal runtime ID.
	TerminalId string `json:"terminalId"`
}

// GetData returns the value of Data.
func (s *ResourceSnapshot) GetData() jx.Raw {
	return s.Data
}

// GetSampledAt returns the value of SampledAt.
func (s *ResourceSnapshot) GetSampledAt() time.Time {
	return s.SampledAt
}

// GetSource returns the value of Source.
func (s *ResourceSnapshot) GetSource() string {
	return s.Source
}

// GetTerminalId returns the value of TerminalId.
func (s *ResourceSnapshot) GetTerminalId() string {
	return s.TerminalId
}

// SetData sets the value of Data.
func (s *ResourceSnapshot) SetData(val jx.Raw) {
	s.Data = val
}

// SetSampledAt sets the value of SampledAt.
func (s *ResourceSnapshot) SetSampledAt(val time.Time) {
	s.SampledAt = val
}

// SetSource sets the value of Source.
func (s *ResourceSnapshot) SetSource(val string) {
	s.Source = val
}

// SetTerminalId sets the value of TerminalId.
func (s *ResourceSnapshot) SetTerminalId(val string) {
	s.TerminalId = val
}

// Ref: #/components/schemas/SandboxExec
type SandboxExec struct {
	// Command argv executed in the sandbox.
	Command   []string  `json:"command"`
	CreatedAt time.Time `json:"createdAt"`
	// Additional environment variables for the exec process.
	Env OptSandboxExecEnv `json:"env"`
	// Runtime error detail when the exec failed.
	Error OptString `json:"error"`
	// Process exit code when the exec has exited.
	ExitCode OptInt64    `json:"exitCode"`
	ExitedAt OptDateTime `json:"exitedAt"`
	// Sandbox exec runtime ID.
	ID string `json:"id"`
	// Caller-supplied exec metadata.
	Metadata OptSandboxExecMetadata `json:"metadata"`
	// Sandbox-local process ID when known.
	Pid       OptInt64    `json:"pid"`
	StartedAt OptDateTime `json:"startedAt"`
	// Current observed exec runtime status.
	Status SandboxExecStatus `json:"status"`
	// Whether the exec process was started with a PTY.
	Tty bool `json:"tty"`
	// Systemd unit or scope name when known.
	Unit OptString `json:"unit"`
	// User identity used to run the exec process.
	User OptSandboxUser `json:"user"`
	// Working directory for the exec process.
	Workdir string `json:"workdir"`
}

// GetCommand returns the value of Command.
func (s *SandboxExec) GetCommand() []string {
	return s.Command
}

// GetCreatedAt returns the value of CreatedAt.
func (s *SandboxExec) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetEnv returns the value of Env.
func (s *SandboxExec) GetEnv() OptSandboxExecEnv {
	return s.Env
}

// GetError returns the value of Error.
func (s *SandboxExec) GetError() OptString {
	return s.Error
}

// GetExitCode returns the value of ExitCode.
func (s *SandboxExec) GetExitCode() OptInt64 {
	return s.ExitCode
}

// GetExitedAt returns the value of ExitedAt.
func (s *SandboxExec) GetExitedAt() OptDateTime {
	return s.ExitedAt
}

// GetID returns the value of ID.
func (s *SandboxExec) GetID() string {
	return s.ID
}

// GetMetadata returns the value of Metadata.
func (s *SandboxExec) GetMetadata() OptSandboxExecMetadata {
	return s.Metadata
}

// GetPid returns the value of Pid.
func (s *SandboxExec) GetPid() OptInt64 {
	return s.Pid
}

// GetStartedAt returns the value of StartedAt.
func (s *SandboxExec) GetStartedAt() OptDateTime {
	return s.StartedAt
}

// GetStatus returns the value of Status.
func (s *SandboxExec) GetStatus() SandboxExecStatus {
	return s.Status
}

// GetTty returns the value of Tty.
func (s *SandboxExec) GetTty() bool {
	return s.Tty
}

// GetUnit returns the value of Unit.
func (s *SandboxExec) GetUnit() OptString {
	return s.Unit
}

// GetUser returns the value of User.
func (s *SandboxExec) GetUser() OptSandboxUser {
	return s.User
}

// GetWorkdir returns the value of Workdir.
func (s *SandboxExec) GetWorkdir() string {
	return s.Workdir
}

// SetCommand sets the value of Command.
func (s *SandboxExec) SetCommand(val []string) {
	s.Command = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *SandboxExec) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetEnv sets the value of Env.
func (s *SandboxExec) SetEnv(val OptSandboxExecEnv) {
	s.Env = val
}

// SetError sets the value of Error.
func (s *SandboxExec) SetError(val OptString) {
	s.Error = val
}

// SetExitCode sets the value of ExitCode.
func (s *SandboxExec) SetExitCode(val OptInt64) {
	s.ExitCode = val
}

// SetExitedAt sets the value of ExitedAt.
func (s *SandboxExec) SetExitedAt(val OptDateTime) {
	s.ExitedAt = val
}

// SetID sets the value of ID.
func (s *SandboxExec) SetID(val string) {
	s.ID = val
}

// SetMetadata sets the value of Metadata.
func (s *SandboxExec) SetMetadata(val OptSandboxExecMetadata) {
	s.Metadata = val
}

// SetPid sets the value of Pid.
func (s *SandboxExec) SetPid(val OptInt64) {
	s.Pid = val
}

// SetStartedAt sets the value of StartedAt.
func (s *SandboxExec) SetStartedAt(val OptDateTime) {
	s.StartedAt = val
}

// SetStatus sets the value of Status.
func (s *SandboxExec) SetStatus(val SandboxExecStatus) {
	s.Status = val
}

// SetTty sets the value of Tty.
func (s *SandboxExec) SetTty(val bool) {
	s.Tty = val
}

// SetUnit sets the value of Unit.
func (s *SandboxExec) SetUnit(val OptString) {
	s.Unit = val
}

// SetUser sets the value of User.
func (s *SandboxExec) SetUser(val OptSandboxUser) {
	s.User = val
}

// SetWorkdir sets the value of Workdir.
func (s *SandboxExec) SetWorkdir(val string) {
	s.Workdir = val
}

// Additional environment variables for the exec process.
type SandboxExecEnv map[string]string

func (s *SandboxExecEnv) init() SandboxExecEnv {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/SandboxExecLogEntry
type SandboxExecLogEntry struct {
	// Base64-encoded raw stream bytes.
	Data []byte `json:"data"`
	// Exec stream this chunk came from.
	Stream SandboxExecLogEntryStream `json:"stream"`
	// Time this exec stream chunk was observed.
	Timestamp time.Time `json:"timestamp"`
}

// GetData returns the value of Data.
func (s *SandboxExecLogEntry) GetData() []byte {
	return s.Data
}

// GetStream returns the value of Stream.
func (s *SandboxExecLogEntry) GetStream() SandboxExecLogEntryStream {
	return s.Stream
}

// GetTimestamp returns the value of Timestamp.
func (s *SandboxExecLogEntry) GetTimestamp() time.Time {
	return s.Timestamp
}

// SetData sets the value of Data.
func (s *SandboxExecLogEntry) SetData(val []byte) {
	s.Data = val
}

// SetStream sets the value of Stream.
func (s *SandboxExecLogEntry) SetStream(val SandboxExecLogEntryStream) {
	s.Stream = val
}

// SetTimestamp sets the value of Timestamp.
func (s *SandboxExecLogEntry) SetTimestamp(val time.Time) {
	s.Timestamp = val
}

// Exec stream this chunk came from.
type SandboxExecLogEntryStream string

const (
	SandboxExecLogEntryStreamInput  SandboxExecLogEntryStream = "input"
	SandboxExecLogEntryStreamOutput SandboxExecLogEntryStream = "output"
	SandboxExecLogEntryStreamStdout SandboxExecLogEntryStream = "stdout"
	SandboxExecLogEntryStreamStderr SandboxExecLogEntryStream = "stderr"
)

// AllValues returns all SandboxExecLogEntryStream values.
func (SandboxExecLogEntryStream) AllValues() []SandboxExecLogEntryStream {
	return []SandboxExecLogEntryStream{
		SandboxExecLogEntryStreamInput,
		SandboxExecLogEntryStreamOutput,
		SandboxExecLogEntryStreamStdout,
		SandboxExecLogEntryStreamStderr,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SandboxExecLogEntryStream) MarshalText() ([]byte, error) {
	switch s {
	case SandboxExecLogEntryStreamInput:
		return []byte(s), nil
	case SandboxExecLogEntryStreamOutput:
		return []byte(s), nil
	case SandboxExecLogEntryStreamStdout:
		return []byte(s), nil
	case SandboxExecLogEntryStreamStderr:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SandboxExecLogEntryStream) UnmarshalText(data []byte) error {
	switch SandboxExecLogEntryStream(data) {
	case SandboxExecLogEntryStreamInput:
		*s = SandboxExecLogEntryStreamInput
		return nil
	case SandboxExecLogEntryStreamOutput:
		*s = SandboxExecLogEntryStreamOutput
		return nil
	case SandboxExecLogEntryStreamStdout:
		*s = SandboxExecLogEntryStreamStdout
		return nil
	case SandboxExecLogEntryStreamStderr:
		*s = SandboxExecLogEntryStreamStderr
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/SandboxExecLogsResponse
type SandboxExecLogsResponse struct {
	Entries []SandboxExecLogEntry `json:"entries"`
}

// GetEntries returns the value of Entries.
func (s *SandboxExecLogsResponse) GetEntries() []SandboxExecLogEntry {
	return s.Entries
}

// SetEntries sets the value of Entries.
func (s *SandboxExecLogsResponse) SetEntries(val []SandboxExecLogEntry) {
	s.Entries = val
}

// Caller-supplied exec metadata.
type SandboxExecMetadata map[string]string

func (s *SandboxExecMetadata) init() SandboxExecMetadata {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

// Current observed exec runtime status.
type SandboxExecStatus string

const (
	SandboxExecStatusStarting SandboxExecStatus = "starting"
	SandboxExecStatusRunning  SandboxExecStatus = "running"
	SandboxExecStatusExited   SandboxExecStatus = "exited"
	SandboxExecStatusFailed   SandboxExecStatus = "failed"
	SandboxExecStatusLost     SandboxExecStatus = "lost"
)

// AllValues returns all SandboxExecStatus values.
func (SandboxExecStatus) AllValues() []SandboxExecStatus {
	return []SandboxExecStatus{
		SandboxExecStatusStarting,
		SandboxExecStatusRunning,
		SandboxExecStatusExited,
		SandboxExecStatusFailed,
		SandboxExecStatusLost,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SandboxExecStatus) MarshalText() ([]byte, error) {
	switch s {
	case SandboxExecStatusStarting:
		return []byte(s), nil
	case SandboxExecStatusRunning:
		return []byte(s), nil
	case SandboxExecStatusExited:
		return []byte(s), nil
	case SandboxExecStatusFailed:
		return []byte(s), nil
	case SandboxExecStatusLost:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SandboxExecStatus) UnmarshalText(data []byte) error {
	switch SandboxExecStatus(data) {
	case SandboxExecStatusStarting:
		*s = SandboxExecStatusStarting
		return nil
	case SandboxExecStatusRunning:
		*s = SandboxExecStatusRunning
		return nil
	case SandboxExecStatusExited:
		*s = SandboxExecStatusExited
		return nil
	case SandboxExecStatusFailed:
		*s = SandboxExecStatusFailed
		return nil
	case SandboxExecStatusLost:
		*s = SandboxExecStatusLost
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/SandboxExecsResponse
type SandboxExecsResponse struct {
	Execs []SandboxExec `json:"execs"`
}

// GetExecs returns the value of Execs.
func (s *SandboxExecsResponse) GetExecs() []SandboxExec {
	return s.Execs
}

// SetExecs sets the value of Execs.
func (s *SandboxExecsResponse) SetExecs(val []SandboxExec) {
	s.Execs = val
}

// Ref: #/components/schemas/SandboxUser
type SandboxUser struct {
	// GID to use inside the sandbox.
	Gid OptInt64 `json:"gid"`
	// User home directory to use inside the sandbox.
	HomeDirectory OptString `json:"homeDirectory"`
	// Username to use inside the sandbox.
	Name OptString `json:"name"`
	// UID to use inside the sandbox.
	UID OptInt64 `json:"uid"`
}

// GetGid returns the value of Gid.
func (s *SandboxUser) GetGid() OptInt64 {
	return s.Gid
}

// GetHomeDirectory returns the value of HomeDirectory.
func (s *SandboxUser) GetHomeDirectory() OptString {
	return s.HomeDirectory
}

// GetName returns the value of Name.
func (s *SandboxUser) GetName() OptString {
	return s.Name
}

// GetUID returns the value of UID.
func (s *SandboxUser) GetUID() OptInt64 {
	return s.UID
}

// SetGid sets the value of Gid.
func (s *SandboxUser) SetGid(val OptInt64) {
	s.Gid = val
}

// SetHomeDirectory sets the value of HomeDirectory.
func (s *SandboxUser) SetHomeDirectory(val OptString) {
	s.HomeDirectory = val
}

// SetName sets the value of Name.
func (s *SandboxUser) SetName(val OptString) {
	s.Name = val
}

// SetUID sets the value of UID.
func (s *SandboxUser) SetUID(val OptInt64) {
	s.UID = val
}

type StreamAgentTerminalResourcesOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s StreamAgentTerminalResourcesOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}
