// Code generated by ogen, DO NOT EDIT.

package sandboxapigen

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AttachAgentTerminal implements attach-agent-terminal operation.
//
// Upgrades to a framed bidirectional stream for a running agent terminal. Closing the stream
// detaches from the terminal and does not stop the underlying agent process.
//
// POST /api/projects/{projectId}/sandboxes/{sandboxId}/agent-terminals/{terminalId}/attach
func (UnimplementedHandler) AttachAgentTerminal(ctx context.Context, params AttachAgentTerminalParams) (r *AttachAgentTerminalSwitchingProtocols, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateAgentTerminal implements create-agent-terminal operation.
//
// Creates an ephemeral terminal/TUI runtime for a coding-agent CLI. When the request is an upgrade
// request, the sandbox agent creates the terminal and switches protocols to the framed bidirectional
// attach stream instead of returning JSON.
//
// POST /api/projects/{projectId}/sandboxes/{sandboxId}/agent-terminals
func (UnimplementedHandler) CreateAgentTerminal(ctx context.Context, req *CreateAgentTerminalRequest, params CreateAgentTerminalParams) (r CreateAgentTerminalRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteAgentTerminal implements delete-agent-terminal operation.
//
// Destroy an agent terminal runtime in a sandbox.
//
// DELETE /api/projects/{projectId}/sandboxes/{sandboxId}/agent-terminals/{terminalId}
func (UnimplementedHandler) DeleteAgentTerminal(ctx context.Context, params DeleteAgentTerminalParams) error {
	return ht.ErrNotImplemented
}

// GetAgentTerminalResources implements get-agent-terminal-resources operation.
//
// Get the latest opaque resource snapshot for an agent terminal.
//
// GET /api/projects/{projectId}/sandboxes/{sandboxId}/agent-terminals/{terminalId}/resources
func (UnimplementedHandler) GetAgentTerminalResources(ctx context.Context, params GetAgentTerminalResourcesParams) (r *ResourceSnapshot, _ error) {
	return r, ht.ErrNotImplemented
}

// ListAgentTerminalEvents implements list-agent-terminal-events operation.
//
// List recent audit events for an agent terminal.
//
// GET /api/projects/{projectId}/sandboxes/{sandboxId}/agent-terminals/{terminalId}/events
func (UnimplementedHandler) ListAgentTerminalEvents(ctx context.Context, params ListAgentTerminalEventsParams) (r *AgentTerminalEventsResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListAgentTerminalResourceHistory implements list-agent-terminal-resource-history operation.
//
// List recent opaque resource snapshots for an agent terminal.
//
// GET /api/projects/{projectId}/sandboxes/{sandboxId}/agent-terminals/{terminalId}/resources/history
func (UnimplementedHandler) ListAgentTerminalResourceHistory(ctx context.Context, params ListAgentTerminalResourceHistoryParams) (r *ResourceHistoryResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListAgentTerminals implements list-agent-terminals operation.
//
// List agent terminal runtimes in a sandbox.
//
// GET /api/projects/{projectId}/sandboxes/{sandboxId}/agent-terminals
func (UnimplementedHandler) ListAgentTerminals(ctx context.Context, params ListAgentTerminalsParams) (r *AgentTerminalsResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// StreamAgentTerminalResources implements stream-agent-terminal-resources operation.
//
// Stream opaque resource snapshots for an agent terminal.
//
// GET /api/projects/{projectId}/sandboxes/{sandboxId}/agent-terminals/{terminalId}/resources/stream
func (UnimplementedHandler) StreamAgentTerminalResources(ctx context.Context, params StreamAgentTerminalResourcesParams) (r StreamAgentTerminalResourcesOK, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorResponseStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorResponseStatusCode) {
	r = new(ErrorResponseStatusCode)
	return r
}
