// Code generated by ogen, DO NOT EDIT.
package supervisorapigen

type SupervisorAttachRes interface {
	supervisorAttachRes()
}

type SupervisorResizeRes interface {
	supervisorResizeRes()
}

type SupervisorSignalRes interface {
	supervisorSignalRes()
}

type SupervisorStatusRes interface {
	supervisorStatusRes()
}
