package cli

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// runSSHConfigWrite runs `ssh-config --write` against fake with HOME and
// XDG_STATE_HOME redirected into the test's temp dirs, so nothing here can
// touch the developer's real ~/.ssh or state directory.
func runSSHConfigWrite(t *testing.T, fake *sshConfigFakeServer) (home, state, stderr string) {
	t.Helper()
	home = t.TempDir()
	state = t.TempDir()
	setHome(t, home)
	t.Setenv("XDG_STATE_HOME", state)

	server := fake.start(t)
	cmd := NewRootCommand()
	var out, errOut strings.Builder
	cmd.SetOut(&out)
	cmd.SetErr(&errOut)
	cmd.SetArgs([]string{"--server", server.URL, "--project", "project-1", "admin", "ssh-config", "--write"})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("execute ssh-config --write: %v", err)
	}
	if out.String() != "" {
		t.Fatalf("--write should not print the config, got:\n%s", out.String())
	}
	return home, state, errOut.String()
}

// setHome redirects the home directory a test writes into, on every platform.
//
// HOME alone is not enough: os.UserHomeDir reads USERPROFILE on Windows and
// ignores HOME entirely, so a test that sets only HOME there writes into the
// developer's own profile — which for these tests means prepending an Include
// line to their real ~/.ssh/config, once per run.
func setHome(t *testing.T, home string) {
	t.Helper()
	t.Setenv("HOME", home)
	t.Setenv("USERPROFILE", home)
}

func managedPaths(state string) (config, knownHosts string) {
	dir := filepath.Join(state, "discobox", "cli", "ssh", resolvedTestProjectID)
	return filepath.Join(dir, "config"), filepath.Join(dir, "known_hosts")
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return string(data)
}

func writeFakeServer() *sshConfigFakeServer {
	return &sshConfigFakeServer{
		ingress:   sshConfigEnabledIngress,
		sandboxes: []sshConfigFakeSandbox{{id: "sbx_devbox00000001", name: "devbox"}},
	}
}

// TestSSHConfigWriteProducesAUsableConfig covers the whole point of --write:
// afterwards ssh can resolve the host, find the key, and verify the server,
// with no further steps.
func TestSSHConfigWriteProducesAUsableConfig(t *testing.T) {
	home, state, stderr := runSSHConfigWrite(t, writeFakeServer())
	configPath, knownHostsPath := managedPaths(state)

	config := readFile(t, configPath)
	for _, want := range []string{
		"Host devbox devbox.discobox.internal sbx_devbox00000001 sbx_devbox00000001.discobox.internal\n",
		"    User sbx_devbox00000001\n",
		"    HostKeyAlias " + resolvedTestProjectID + ".discobox.internal\n",
		"    IdentitiesOnly yes\n",
		"    UserKnownHostsFile " + knownHostsPath + "\n",
	} {
		if !strings.Contains(config, want) {
			t.Fatalf("managed config missing %q:\n%s", want, config)
		}
	}
	// Written files are rewritten wholesale, so say so where someone will see it.
	if !strings.HasPrefix(config, "# Generated by") {
		t.Fatalf("managed config has no generated-file header:\n%s", config)
	}

	// The stanzas reach the server through a ProxyCommand, so what ssh runs
	// has to be in the file it just wrote.
	if !strings.Contains(config, " admin ssh-proxy\n") {
		t.Fatalf("managed config has no ProxyCommand:\n%s", config)
	}

	if got := readFile(t, knownHostsPath); got != resolvedTestProjectID+".discobox.internal ssh-ed25519 AAAAfakehostkey==\n" {
		t.Fatalf("known_hosts = %q", got)
	}

	userConfig := readFile(t, filepath.Join(home, ".ssh", "config"))
	if userConfig != "Include "+configPath+"\n" {
		t.Fatalf("user ssh config = %q", userConfig)
	}
	if !strings.Contains(stderr, configPath) {
		t.Fatalf("stderr should report what was written, got %q", stderr)
	}
}

// TestSSHConfigWriteIsIdempotent: this is a command people re-run whenever they
// create a sandbox, so it must not accumulate Include lines.
func TestSSHConfigWriteIsIdempotent(t *testing.T) {
	home, state, _ := runSSHConfigWrite(t, writeFakeServer())
	configPath, _ := managedPaths(state)
	userConfigPath := filepath.Join(home, ".ssh", "config")
	first := readFile(t, userConfigPath)

	// Re-run in the same HOME/state.
	server := writeFakeServer().start(t)
	cmd := NewRootCommand()
	cmd.SetOut(new(strings.Builder))
	var errOut strings.Builder
	cmd.SetErr(&errOut)
	cmd.SetArgs([]string{"--server", server.URL, "--project", "project-1", "admin", "ssh-config", "--write"})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("second execute: %v", err)
	}

	if got := readFile(t, userConfigPath); got != first {
		t.Fatalf("second run changed ~/.ssh/config:\n%q\nwant\n%q", got, first)
	}
	if strings.Count(readFile(t, userConfigPath), "Include "+configPath) != 1 {
		t.Fatal("the Include line was duplicated")
	}
	if strings.Contains(errOut.String(), "added an Include") {
		t.Fatalf("second run claimed to add an Include again: %q", errOut.String())
	}
}

// TestSSHConfigWritePreservesAndPrecedesExistingConfig: ssh takes the first
// value obtained for each keyword, so an Include after a user's `Host *` block
// would lose every setting that block also sets.
func TestSSHConfigWritePreservesAndPrecedesExistingConfig(t *testing.T) {
	home := t.TempDir()
	state := t.TempDir()
	setHome(t, home)
	t.Setenv("XDG_STATE_HOME", state)
	if err := os.MkdirAll(filepath.Join(home, ".ssh"), 0o700); err != nil {
		t.Fatal(err)
	}
	existing := "Host *\n    IdentityFile ~/.ssh/id_rsa\n\nHost work\n    HostName work.example.com\n"
	userConfigPath := filepath.Join(home, ".ssh", "config")
	if err := os.WriteFile(userConfigPath, []byte(existing), 0o600); err != nil {
		t.Fatal(err)
	}

	server := writeFakeServer().start(t)
	cmd := NewRootCommand()
	cmd.SetOut(new(strings.Builder))
	cmd.SetErr(new(strings.Builder))
	cmd.SetArgs([]string{"--server", server.URL, "--project", "project-1", "admin", "ssh-config", "--write"})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("execute ssh-config --write: %v", err)
	}

	got := readFile(t, userConfigPath)
	if !strings.HasPrefix(got, "Include ") {
		t.Fatalf("the Include must come first, got:\n%s", got)
	}
	if !strings.Contains(got, existing) {
		t.Fatalf("the user's existing config was not preserved verbatim:\n%s", got)
	}
}

func TestHasSSHConfigInclude(t *testing.T) {
	const managed = "/home/u/.local/state/discobox/cli/ssh/config"
	for _, tc := range []struct {
		name   string
		config string
		want   bool
	}{
		{name: "plain", config: "Include " + managed + "\n", want: true},
		{name: "indented and mixed case", config: "  include " + managed + "\n", want: true},
		{name: "quoted", config: `Include "` + managed + `"` + "\n", want: true},
		{name: "among several paths", config: "Include ~/.ssh/other " + managed + "\n", want: true},
		{name: "commented out does not count", config: "# Include " + managed + "\n", want: false},
		{name: "a different path", config: "Include ~/.ssh/other\n", want: false},
		{name: "empty", config: "", want: false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			if got := (sshTarget{}).hasInclude(tc.config, managed); got != tc.want {
				t.Fatalf("hasInclude(%q) = %v, want %v", tc.config, got, tc.want)
			}
		})
	}
}

// TestSSHConfigWriteEmptiesTheConfigWhenTheProjectDoes: the written files
// mirror the server, so a project whose last sandbox is gone must stop offering
// stanzas for it rather than leaving them to resolve to nothing.
func TestSSHConfigWriteEmptiesTheConfigWhenTheProjectDoes(t *testing.T) {
	home := t.TempDir()
	state := t.TempDir()
	setHome(t, home)
	t.Setenv("XDG_STATE_HOME", state)
	configPath, knownHostsPath := managedPaths(state)

	// First a run with a sandbox, so there are stanzas to be replaced.
	populated := writeFakeServer()
	server := populated.start(t)
	run := func(url string) {
		cmd := NewRootCommand()
		cmd.SetOut(new(strings.Builder))
		cmd.SetErr(new(strings.Builder))
		cmd.SetArgs([]string{"--server", url, "--project", "project-1", "admin", "ssh-config", "--write"})
		if err := cmd.Execute(); err != nil {
			t.Fatalf("execute ssh-config --write: %v", err)
		}
	}
	run(server.URL)
	if !strings.Contains(readFile(t, configPath), "Host ") {
		t.Fatal("setup did not write any stanzas")
	}

	emptied := &sshConfigFakeServer{ingress: sshConfigEnabledIngress, sandboxes: nil}
	run(emptied.start(t).URL)

	config := readFile(t, configPath)
	if strings.Contains(config, "Host ") {
		t.Fatalf("stale stanzas survived the project emptying:\n%s", config)
	}
	if !strings.HasPrefix(config, "# Generated by") {
		t.Fatalf("the emptied config lost its header:\n%s", config)
	}
	// The host key is the server's, not a sandbox's, so it stays: the next run
	// with a sandbox in it needs no second trip to re-pin the same server.
	if got := readFile(t, knownHostsPath); !strings.Contains(got, "ssh-ed25519") {
		t.Fatalf("known_hosts lost the server's key, got %q", got)
	}
	// The Include must survive: it is what makes the next populated run take
	// effect without the user touching ~/.ssh/config again.
	if !strings.Contains(readFile(t, filepath.Join(home, ".ssh", "config")), "Include "+configPath) {
		t.Fatal("the Include was dropped when the project emptied")
	}
}

// TestSSHConfigWriteIsScopedPerProject: a run only knows about one project, so
// a shared file would delete every other project's stanzas each time.
func TestSSHConfigWriteIsScopedPerProject(t *testing.T) {
	home := t.TempDir()
	state := t.TempDir()
	setHome(t, home)
	t.Setenv("XDG_STATE_HOME", state)

	// Two projects on two servers, each resolving to its own ID.
	first := writeFakeServer()
	firstURL := first.start(t).URL
	second := &sshConfigFakeServer{
		ingress:   sshConfigEnabledIngress,
		sandboxes: []sshConfigFakeSandbox{{id: "sbx_other000000001", name: "otherbox"}},
	}
	secondURL := second.start(t).URL

	for _, url := range []string{firstURL, secondURL} {
		cmd := NewRootCommand()
		cmd.SetOut(new(strings.Builder))
		cmd.SetErr(new(strings.Builder))
		cmd.SetArgs([]string{"--server", url, "--project", "project-1", "admin", "ssh-config", "--write"})
		if err := cmd.Execute(); err != nil {
			t.Fatalf("execute ssh-config --write: %v", err)
		}
	}

	// Both servers resolve project-1 to the same ID here, so this asserts the
	// shape: one directory per resolved project, named after it.
	configPath, _ := managedPaths(state)
	if !strings.Contains(configPath, resolvedTestProjectID) {
		t.Fatalf("managed config path is not project scoped: %s", configPath)
	}
	config := readFile(t, configPath)
	if !strings.Contains(config, "project "+resolvedTestProjectID) {
		t.Fatalf("the header should name the project it belongs to:\n%s", config)
	}
	// The Include names this project's file specifically, so adding a second
	// project adds a line rather than rewriting the first one's.
	userConfig := readFile(t, filepath.Join(home, ".ssh", "config"))
	if strings.Count(userConfig, "Include ") != 1 {
		t.Fatalf("same project written twice should keep one Include:\n%s", userConfig)
	}
	if !strings.Contains(userConfig, resolvedTestProjectID) {
		t.Fatalf("the Include should name the project's own file:\n%s", userConfig)
	}
}

// An Include this CLI wrote to a state directory it no longer uses is removed
// rather than left behind.
//
// It is not tidiness: ssh fails outright on an Include it will not read, and
// the file at the old path is exactly the one whose permissions it refuses on
// Windows. Left there, the line breaks every connection through this config —
// including the one the new Include was written to make work.
func TestSSHConfigWriteDropsAnIncludeFromAnOldStateDirectory(t *testing.T) {
	home, state := t.TempDir(), t.TempDir()
	setHome(t, home)
	t.Setenv("XDG_STATE_HOME", state)

	// What a previous version left: its own Include, plus one of the user's
	// own that has nothing to do with us.
	oldState := filepath.Join(t.TempDir(), "old")
	stale := filepath.Join(oldState, "discobox", "cli", "ssh", "proj_old0000000001", "config")
	userConfig := filepath.Join(home, ".ssh", "config")
	if err := os.MkdirAll(filepath.Dir(userConfig), 0o700); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	existing := "Include " + stale + "\n\nInclude " + filepath.Join(home, "work", "ssh_config") + "\n\nHost *\n    IdentityFile ~/.ssh/id_rsa\n"
	if err := os.WriteFile(userConfig, []byte(existing), 0o600); err != nil {
		t.Fatalf("write: %v", err)
	}

	server := writeFakeServer().start(t)
	cmd := NewRootCommand()
	var out, errOut strings.Builder
	cmd.SetOut(&out)
	cmd.SetErr(&errOut)
	cmd.SetArgs([]string{"--server", server.URL, "--project", "project-1", "admin", "ssh-config", "--write"})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("execute ssh-config --write: %v", err)
	}

	got := readFile(t, userConfig)
	if strings.Contains(got, stale) {
		t.Fatalf("the stale Include survived:\n%s", got)
	}
	if !strings.Contains(errOut.String(), "removed a stale Include") {
		t.Fatalf("removing it should be reported, got:\n%s", errOut.String())
	}
	// The user's own Include and their own settings are none of our business.
	for _, want := range []string{filepath.Join(home, "work", "ssh_config"), "IdentityFile ~/.ssh/id_rsa"} {
		if !strings.Contains(got, want) {
			t.Fatalf("the rewrite dropped %q:\n%s", want, got)
		}
	}
	config, _ := managedPaths(state)
	if !strings.Contains(got, "Include "+config) {
		t.Fatalf("the new Include is missing:\n%s", got)
	}
}

// A second project's Include lives in the same state directory and is not
// stale: one per project is the design.
func TestSSHConfigWriteKeepsOtherProjectsIncludes(t *testing.T) {
	home, state := t.TempDir(), t.TempDir()
	setHome(t, home)
	t.Setenv("XDG_STATE_HOME", state)

	other := filepath.Join(state, "discobox", "cli", "ssh", "proj_other000000001", "config")
	userConfig := filepath.Join(home, ".ssh", "config")
	if err := os.MkdirAll(filepath.Dir(userConfig), 0o700); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(userConfig, []byte("Include "+other+"\n"), 0o600); err != nil {
		t.Fatalf("write: %v", err)
	}

	server := writeFakeServer().start(t)
	cmd := NewRootCommand()
	cmd.SetOut(&strings.Builder{})
	cmd.SetErr(&strings.Builder{})
	cmd.SetArgs([]string{"--server", server.URL, "--project", "project-1", "admin", "ssh-config", "--write"})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("execute ssh-config --write: %v", err)
	}

	if got := readFile(t, userConfig); !strings.Contains(got, other) {
		t.Fatalf("another project's Include was dropped:\n%s", got)
	}
}
