package cli

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	apiclientgen "github.com/obot-platform/discobox/api/gen"
	apimodel "github.com/obot-platform/discobox/api/model"
)

// The written artifacts live beside the generated key, under the CLI's own
// state directory, and ~/.ssh gains one line per project: an Include pointing
// at that project's file. Keeping the generated files out of ~/.ssh means this
// command never has to parse, merge into, or risk mangling a config the user
// maintains by hand — it owns each project's files outright and rewrites them
// wholesale.
//
// The files are per project rather than one merged config because a run only
// ever knows about one project: writing a shared file would delete the stanzas
// of every other project each time, and two projects can live on different
// servers with different host keys and addresses.
func managedSSHConfigPath(projectID string) string {
	return filepath.Join(cliStateDir(), "ssh", projectID, "config")
}

func managedKnownHostsPath(projectID string) string {
	return filepath.Join(cliStateDir(), "ssh", projectID, "known_hosts")
}

func userSSHConfigPath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".ssh", "config"), nil
}

// knownHostsFileFor returns the UserKnownHostsFile the stanzas should carry.
// Printed output gets none: it would name a file this run never wrote.
func knownHostsFileFor(write bool, projectID string) string {
	if !write {
		return ""
	}
	return managedKnownHostsPath(projectID)
}

type sshConfigRender struct {
	sandboxes      []apimodel.Sandbox
	host           string
	port           int
	identityFile   string
	knownHostsFile string
}

// renderSSHConfig builds the Host stanzas. It is shared by both output modes so
// what gets written is exactly what would have been printed, apart from the
// UserKnownHostsFile only the written form can honestly name.
func renderSSHConfig(in sshConfigRender) string {
	patterns := sshConfigHostPatterns(in.sandboxes)
	var out strings.Builder
	for i, sandbox := range in.sandboxes {
		if len(patterns[i]) == 0 {
			// Every candidate was claimed by another sandbox. Emitting `Host`
			// with no patterns is an ssh_config syntax error that would break
			// the whole file, so say what happened instead.
			fmt.Fprintf(&out, "# %s (%s) has no unambiguous host alias and was skipped\n\n",
				sandbox.Config.Name, sandbox.ID)
			continue
		}
		fmt.Fprintf(&out, "Host %s\n", strings.Join(patterns[i], " "))
		fmt.Fprintf(&out, "    HostName %s\n", in.host)
		fmt.Fprintf(&out, "    Port %d\n", in.port)
		fmt.Fprintf(&out, "    User %s\n", sandbox.ID)
		fmt.Fprintf(&out, "    IdentityFile %s\n", in.identityFile)
		// Without IdentitiesOnly, ssh offers every agent key before this one
		// and can exhaust MaxAuthTries before reaching it.
		fmt.Fprintf(&out, "    IdentitiesOnly yes\n")
		if in.knownHostsFile != "" {
			fmt.Fprintf(&out, "    UserKnownHostsFile %s\n", in.knownHostsFile)
		}
		if i < len(in.sandboxes)-1 {
			fmt.Fprintln(&out)
		}
	}
	return out.String()
}

func managedConfigHeader(projectID string) string {
	return "# Generated by `disco box ssh-config --write` for project " + projectID + ".\n" +
		"# This file is rewritten on every run: edit ~/.ssh/config instead, which\n" +
		"# Includes it.\n\n"
}

// writeManagedSSHConfig writes the stanzas and the server's host key, then
// ensures ~/.ssh/config includes them.
//
// stanzas is empty when the server has no SSH ingress, and that writes an empty
// config rather than skipping the write: these files mirror the server, so a
// project that stopped offering SSH must stop offering stanzas that point at a
// port nothing answers on.
func writeManagedSSHConfig(cmd *cobra.Command, projectID, stanzas, knownHostsHost, hostKey string) error {
	configPath, knownHostsPath := managedSSHConfigPath(projectID), managedKnownHostsPath(projectID)
	if err := os.MkdirAll(filepath.Dir(configPath), 0o700); err != nil {
		return fmt.Errorf("create SSH config directory: %w", err)
	}
	// Pinning the host key here rather than in ~/.ssh/known_hosts keeps
	// StrictHostKeyChecking meaningful without editing a file that records the
	// user's trust in every other host they use.
	knownHosts := ""
	if hostKey != "" {
		knownHosts = knownHostsHost + " " + hostKey + "\n"
	}
	if err := os.WriteFile(knownHostsPath, []byte(knownHosts), 0o644); err != nil {
		return fmt.Errorf("write known_hosts: %w", err)
	}
	if err := os.WriteFile(configPath, []byte(managedConfigHeader(projectID)+stanzas), 0o600); err != nil {
		return fmt.Errorf("write SSH config: %w", err)
	}

	userConfig, err := userSSHConfigPath()
	if err != nil {
		return err
	}
	added, err := ensureSSHConfigInclude(userConfig, configPath)
	if err != nil {
		return err
	}
	stderr := cmd.ErrOrStderr()
	fmt.Fprintf(stderr, "wrote %s\n", configPath)
	if added {
		fmt.Fprintf(stderr, "added an Include for it to %s\n", userConfig)
	}
	return nil
}

// ensureSSHConfigInclude adds an Include for managed to the user's ssh_config,
// reporting whether it had to. It is idempotent, so repeated --write runs leave
// one line rather than a growing pile.
//
// The line goes at the top because ssh_config takes the *first* value obtained
// for each keyword: an Include placed after a `Host *` block the user already
// has would lose every setting that block also sets.
func ensureSSHConfigInclude(userConfig, managed string) (bool, error) {
	include := "Include " + managed
	existing, err := os.ReadFile(userConfig)
	if err != nil && !os.IsNotExist(err) {
		return false, fmt.Errorf("read %s: %w", userConfig, err)
	}
	if hasSSHConfigInclude(string(existing), managed) {
		return false, nil
	}
	if err := os.MkdirAll(filepath.Dir(userConfig), 0o700); err != nil {
		return false, fmt.Errorf("create SSH directory: %w", err)
	}
	body := include + "\n"
	if len(existing) > 0 {
		body += "\n" + string(existing)
	}
	// Written through a temp file in the same directory so an interrupted run
	// cannot leave the user with a truncated ssh_config.
	tmp, err := os.CreateTemp(filepath.Dir(userConfig), ".discobox-ssh-config-*")
	if err != nil {
		return false, fmt.Errorf("write %s: %w", userConfig, err)
	}
	defer os.Remove(tmp.Name())
	if err := tmp.Chmod(0o600); err != nil {
		_ = tmp.Close()
		return false, fmt.Errorf("write %s: %w", userConfig, err)
	}
	if _, err := tmp.WriteString(body); err != nil {
		_ = tmp.Close()
		return false, fmt.Errorf("write %s: %w", userConfig, err)
	}
	if err := tmp.Close(); err != nil {
		return false, fmt.Errorf("write %s: %w", userConfig, err)
	}
	if err := os.Rename(tmp.Name(), userConfig); err != nil {
		return false, fmt.Errorf("write %s: %w", userConfig, err)
	}
	return true, nil
}

// hasSSHConfigInclude reports whether config already includes managed, matching
// on the path rather than the whole line so an Include the user reformatted
// (extra spacing, quotes) is still recognized and not duplicated.
func hasSSHConfigInclude(config, managed string) bool {
	scanner := bufio.NewScanner(strings.NewReader(config))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) < 2 || !strings.EqualFold(fields[0], "include") {
			continue
		}
		for _, field := range fields[1:] {
			if strings.Trim(field, `"'`) == managed {
				return true
			}
		}
	}
	return false
}

// resolveProjectID turns whatever -p was given into the project's real ID.
// "default" is a server-side alias rather than an identifier, and the written
// files are named after the project, so without this the same project reached
// two ways would own two files and two Include lines.
func (a *App) resolveProjectID(cmd *cobra.Command, client *apiclientgen.Client, projectID string) (string, error) {
	res, err := client.GetProject(cmd.Context(), apiclientgen.GetProjectParams{ProjectId: projectID})
	if err != nil {
		return "", err
	}
	project, err := expectResponse[apimodel.Project](res)
	if err != nil {
		return "", err
	}
	if strings.TrimSpace(project.ID) == "" {
		return "", fmt.Errorf("server returned no ID for project %q", projectID)
	}
	return project.ID, nil
}
