package cli

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	apiclientgen "github.com/discobox-ai/discobox/api/gen"
	apimodel "github.com/discobox-ai/discobox/api/model"
)

// The written artifacts live beside the generated key, under the CLI's own
// state directory, and ~/.ssh gains one line per project: an Include pointing
// at that project's file. Keeping the generated files out of ~/.ssh means this
// command never has to parse, merge into, or risk mangling a config the user
// maintains by hand — it owns each project's files outright and rewrites them
// wholesale.
//
// The files are per project rather than one merged config because a run only
// ever knows about one project: writing a shared file would delete the stanzas
// of every other project each time, and two projects can live on different
// servers with different host keys and addresses.
func managedSSHConfigPath(projectID string) string {
	return filepath.Join(cliStateDir(), "ssh", projectID, "config")
}

func managedKnownHostsPath(projectID string) string {
	return filepath.Join(cliStateDir(), "ssh", projectID, "known_hosts")
}

func userSSHConfigPath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".ssh", "config"), nil
}

// knownHostsFileFor returns the UserKnownHostsFile the stanzas should carry.
// Printed output gets none: it would name a file this run never wrote.
func knownHostsFileFor(write bool, projectID string) string {
	if !write {
		return ""
	}
	return managedKnownHostsPath(projectID)
}

type sshConfigRender struct {
	sandboxes []apimodel.Sandbox

	// proxyCommand carries the connection. Nothing here names an address: the
	// server binds no SSH port, so the stanzas reach it the same way every
	// other request does (ADR 0057).
	proxyCommand string

	// hostKeyAlias is what the stanzas verify the host key under, and so the
	// host field of the matching known_hosts line. Without an address there is
	// nothing for ssh to derive one from.
	hostKeyAlias string

	identityFile   string
	knownHostsFile string
}

// renderSSHConfig builds the Host stanzas. It is shared by both output modes so
// what gets written is exactly what would have been printed, apart from the
// UserKnownHostsFile only the written form can honestly name.
func renderSSHConfig(in sshConfigRender) string {
	patterns := sshConfigHostPatterns(in.sandboxes)
	var out strings.Builder
	for i, sandbox := range in.sandboxes {
		if len(patterns[i]) == 0 {
			// Every candidate was claimed by another sandbox. Emitting `Host`
			// with no patterns is an ssh_config syntax error that would break
			// the whole file, so say what happened instead.
			fmt.Fprintf(&out, "# %s (%s) has no unambiguous host alias and was skipped\n\n",
				sandbox.Config.Name, sandbox.ID)
			continue
		}
		fmt.Fprintf(&out, "Host %s\n", strings.Join(patterns[i], " "))
		// No HostName and no Port: there is no address to dial. ssh runs the
		// ProxyCommand and speaks its protocol over its stdio.
		fmt.Fprintf(&out, "    ProxyCommand %s\n", in.proxyCommand)
		fmt.Fprintf(&out, "    User %s\n", sandbox.ID)
		fmt.Fprintf(&out, "    IdentityFile %s\n", in.identityFile)
		// Without IdentitiesOnly, ssh offers every agent key before this one
		// and can exhaust MaxAuthTries before reaching it.
		fmt.Fprintf(&out, "    IdentitiesOnly yes\n")
		// One name for the server's key, across every alias, so one known_hosts
		// line covers the whole project.
		fmt.Fprintf(&out, "    HostKeyAlias %s\n", in.hostKeyAlias)
		if in.knownHostsFile != "" {
			fmt.Fprintf(&out, "    UserKnownHostsFile %s\n", in.knownHostsFile)
		}
		if i < len(in.sandboxes)-1 {
			fmt.Fprintln(&out)
		}
	}
	return out.String()
}

func managedConfigHeader(projectID string) string {
	return "# Generated by `discobox admin ssh-config --write` for project " + projectID + ".\n" +
		"# This file is rewritten on every run: edit ~/.ssh/config instead, which\n" +
		"# Includes it.\n\n"
}

// writeManagedSSHConfig writes the stanzas and the server's host key, then
// ensures ~/.ssh/config includes them.
//
// stanzas is empty when the project has no sandboxes, and that writes an empty
// config rather than skipping the write: these files mirror the server, so a
// project whose last sandbox is gone must stop offering stanzas for it.
func writeManagedSSHConfig(cmd *cobra.Command, projectID, stanzas, knownHostsHost, hostKey string) error {
	configPath, knownHostsPath := managedSSHConfigPath(projectID), managedKnownHostsPath(projectID)
	if err := ensureStateDir(filepath.Dir(configPath)); err != nil {
		return fmt.Errorf("create SSH config directory: %w", err)
	}
	// Pinning the host key here rather than in ~/.ssh/known_hosts keeps
	// StrictHostKeyChecking meaningful without editing a file that records the
	// user's trust in every other host they use.
	knownHosts := ""
	if hostKey != "" {
		knownHosts = knownHostsHost + " " + hostKey + "\n"
	}
	// 0600 like the config beside it: a known_hosts file is public
	// information, but nothing other than this user needs to read it.
	if err := os.WriteFile(knownHostsPath, []byte(knownHosts), 0o600); err != nil {
		return fmt.Errorf("write known_hosts: %w", err)
	}
	if err := os.WriteFile(configPath, []byte(managedConfigHeader(projectID)+stanzas), 0o600); err != nil {
		return fmt.Errorf("write SSH config: %w", err)
	}
	// The files as well as the directory they are in: a run before this one may
	// have left them readable by whoever the profile grants, and ssh refuses a
	// config it does not like the look of rather than ignoring it.
	for _, path := range []string{knownHostsPath, configPath} {
		if err := restrictToUser(path); err != nil {
			return fmt.Errorf("restrict %s to this user: %w", filepath.Base(path), err)
		}
	}

	userConfig, err := userSSHConfigPath()
	if err != nil {
		return err
	}
	added, dropped, err := ensureSSHConfigInclude(userConfig, configPath)
	if err != nil {
		return err
	}
	stderr := cmd.ErrOrStderr()
	fmt.Fprintf(stderr, "wrote %s\n", configPath)
	if added {
		fmt.Fprintf(stderr, "added an Include for it to %s\n", userConfig)
	}
	for _, stale := range dropped {
		fmt.Fprintf(stderr, "removed a stale Include of %s\n", stale)
	}
	return nil
}

// ensureSSHConfigInclude adds an Include for managed to the user's ssh_config
// and drops the ones this CLI wrote that no longer point anywhere it manages,
// reporting what it did on each count. It is idempotent, so repeated --write
// runs leave one line rather than a growing pile.
//
// The line goes at the top because ssh_config takes the *first* value obtained
// for each keyword: an Include placed after a `Host *` block the user already
// has would lose every setting that block also sets.
//
// Dropping the stale ones is not tidiness. ssh fails outright on an Include it
// will not read — one whose permissions it dislikes, in particular — so a line
// left pointing into a directory this CLI has moved out of breaks every
// connection through this config, including the ones the new line was written
// to make work.
func ensureSSHConfigInclude(userConfig, managed string) (bool, []string, error) {
	include := "Include " + managed
	existing, err := os.ReadFile(userConfig)
	if err != nil && !os.IsNotExist(err) {
		return false, nil, fmt.Errorf("read %s: %w", userConfig, err)
	}
	cleaned, dropped := dropStaleManagedIncludes(string(existing), managed)
	if hasSSHConfigInclude(cleaned, managed) && len(dropped) == 0 {
		return false, nil, nil
	}
	if err := os.MkdirAll(filepath.Dir(userConfig), 0o700); err != nil {
		return false, nil, fmt.Errorf("create SSH directory: %w", err)
	}
	added := !hasSSHConfigInclude(cleaned, managed)
	body := cleaned
	if added {
		body = include + "\n"
		if len(cleaned) > 0 {
			body += "\n" + cleaned
		}
	}
	// Written through a temp file in the same directory so an interrupted run
	// cannot leave the user with a truncated ssh_config.
	tmp, err := os.CreateTemp(filepath.Dir(userConfig), ".discobox-ssh-config-*")
	if err != nil {
		return false, nil, fmt.Errorf("write %s: %w", userConfig, err)
	}
	defer os.Remove(tmp.Name())
	if err := tmp.Chmod(0o600); err != nil {
		_ = tmp.Close()
		return false, nil, fmt.Errorf("write %s: %w", userConfig, err)
	}
	// Chmod is the whole story on Unix and none of it on Windows, where the
	// file this replaces is one ssh reads and checks. Restricted before the
	// rename, so what lands is already private.
	if err := restrictToUser(tmp.Name()); err != nil {
		_ = tmp.Close()
		return false, nil, fmt.Errorf("write %s: %w", userConfig, err)
	}
	if _, err := tmp.WriteString(body); err != nil {
		_ = tmp.Close()
		return false, nil, fmt.Errorf("write %s: %w", userConfig, err)
	}
	if err := tmp.Close(); err != nil {
		return false, nil, fmt.Errorf("write %s: %w", userConfig, err)
	}
	if err := os.Rename(tmp.Name(), userConfig); err != nil {
		return false, nil, fmt.Errorf("write %s: %w", userConfig, err)
	}
	return added, dropped, nil
}

// dropStaleManagedIncludes removes Include lines that name a file this CLI
// generates but no longer writes, returning the config without them and the
// paths dropped.
//
// A managed path is recognized by its shape — <anything>/discobox/cli/ssh/<project>/config
// — which is what this CLI has always written and nothing else has reason to.
// Anything matching that shape and sitting outside the current state directory
// was written by an older version that kept its state somewhere else, and is
// now a path with nothing behind it or, worse, a file whose permissions ssh
// refuses. Includes under the current state directory are left alone however
// many there are: one per project is the design.
//
// The user's own Includes are untouched. Only this shape is ours to remove.
func dropStaleManagedIncludes(config, managed string) (string, []string) {
	state := filepath.Clean(cliStateDir())
	var kept []string
	var dropped []string
	for _, line := range strings.Split(config, "\n") {
		if path, ok := sshConfigIncludePath(line); ok &&
			isManagedSSHConfigPath(path) &&
			!strings.EqualFold(path, filepath.Clean(managed)) &&
			!withinDir(state, path) {
			dropped = append(dropped, path)
			continue
		}
		kept = append(kept, line)
	}
	if len(dropped) == 0 {
		return config, nil
	}
	// A dropped line leaves a blank behind, and a run of them accumulates: the
	// file is rewritten without the gaps rather than growing one per removal.
	return collapseBlankRuns(strings.Join(kept, "\n")), dropped
}

// sshConfigIncludePath is the path an Include line names, if the line is one.
func sshConfigIncludePath(line string) (string, bool) {
	trimmed := strings.TrimSpace(line)
	if trimmed == "" || strings.HasPrefix(trimmed, "#") {
		return "", false
	}
	fields := strings.Fields(trimmed)
	// Exactly one path: an Include naming several files is not one of ours, and
	// picking one of them out of it would be rewriting a line we did not write.
	if len(fields) != 2 || !strings.EqualFold(fields[0], "include") {
		return "", false
	}
	return filepath.Clean(strings.Trim(fields[1], `"`)), true
}

// isManagedSSHConfigPath reports whether path has the shape this CLI writes:
// .../discobox/cli/ssh/<project>/config.
func isManagedSSHConfigPath(path string) bool {
	dir, file := filepath.Split(filepath.Clean(path))
	if !strings.EqualFold(file, "config") {
		return false
	}
	parts := strings.Split(filepath.ToSlash(filepath.Clean(dir)), "/")
	if len(parts) < 4 {
		return false
	}
	tail := parts[len(parts)-4:]
	return strings.EqualFold(tail[0], "discobox") &&
		strings.EqualFold(tail[1], "cli") &&
		strings.EqualFold(tail[2], "ssh")
}

// withinDir reports whether path is dir or sits under it.
func withinDir(dir, path string) bool {
	rel, err := filepath.Rel(filepath.Clean(dir), filepath.Clean(path))
	if err != nil {
		return false
	}
	return rel != ".." && !strings.HasPrefix(rel, ".."+string(filepath.Separator))
}

// collapseBlankRuns leaves at most one blank line where there were several, so
// removing lines from the middle of a config does not leave it full of holes.
func collapseBlankRuns(config string) string {
	var out []string
	blank := false
	for _, line := range strings.Split(config, "\n") {
		if strings.TrimSpace(line) == "" {
			if blank {
				continue
			}
			blank = true
		} else {
			blank = false
		}
		out = append(out, line)
	}
	return strings.Join(out, "\n")
}

// hasSSHConfigInclude reports whether config already includes managed, matching
// on the path rather than the whole line so an Include the user reformatted
// (extra spacing, quotes) is still recognized and not duplicated.
func hasSSHConfigInclude(config, managed string) bool {
	scanner := bufio.NewScanner(strings.NewReader(config))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) < 2 || !strings.EqualFold(fields[0], "include") {
			continue
		}
		for _, field := range fields[1:] {
			if strings.Trim(field, `"'`) == managed {
				return true
			}
		}
	}
	return false
}

// concreteProjectID turns whatever -p was given into the project's real ID.
//
// It is deliberately not id.go's resolveProjectID, which passes the "default"
// alias through untouched for the server to resolve. That is right for a
// request — the server is the only side that knows which project carries the
// default flag — and wrong here: these files are *named* after the project, so
// leaving the alias unresolved is exactly how one project ends up owning two
// files and two Include lines.
func (a *App) concreteProjectID(cmd *cobra.Command, client *apiclientgen.Client, projectID string) (string, error) {
	res, err := client.GetProject(cmd.Context(), apiclientgen.GetProjectParams{ProjectId: projectID})
	if err != nil {
		return "", err
	}
	project, err := expectResponse[apimodel.Project](res)
	if err != nil {
		return "", err
	}
	if strings.TrimSpace(project.ID) == "" {
		return "", fmt.Errorf("server returned no ID for project %q", projectID)
	}
	return project.ID, nil
}
