package cli

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// runSSHConfigWrite runs `ssh-config --write` against fake with HOME and
// XDG_STATE_HOME redirected into the test's temp dirs, so nothing here can
// touch the developer's real ~/.ssh or state directory.
func runSSHConfigWrite(t *testing.T, fake *sshConfigFakeServer) (home, state, stderr string) {
	t.Helper()
	home = t.TempDir()
	state = t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("XDG_STATE_HOME", state)

	server := fake.start(t)
	cmd := NewRootCommand()
	var out, errOut strings.Builder
	cmd.SetOut(&out)
	cmd.SetErr(&errOut)
	cmd.SetArgs([]string{"--server", server.URL, "--project", "project-1", "box", "ssh-config", "--write"})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("execute ssh-config --write: %v", err)
	}
	if out.String() != "" {
		t.Fatalf("--write should not print the config, got:\n%s", out.String())
	}
	return home, state, errOut.String()
}

func managedPaths(state string) (config, knownHosts string) {
	dir := filepath.Join(state, "discobox", "cli", "ssh")
	return filepath.Join(dir, "config"), filepath.Join(dir, "known_hosts")
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return string(data)
}

func writeFakeServer() *sshConfigFakeServer {
	return &sshConfigFakeServer{
		ingress:   sshConfigEnabledIngress,
		sandboxes: []sshConfigFakeSandbox{{id: "sbx_devbox00000001", name: "devbox"}},
	}
}

// TestSSHConfigWriteProducesAUsableConfig covers the whole point of --write:
// afterwards ssh can resolve the host, find the key, and verify the server,
// with no further steps.
func TestSSHConfigWriteProducesAUsableConfig(t *testing.T) {
	home, state, stderr := runSSHConfigWrite(t, writeFakeServer())
	configPath, knownHostsPath := managedPaths(state)

	config := readFile(t, configPath)
	for _, want := range []string{
		"Host devbox devbox.discobox.internal sbx_devbox00000001 sbx_devbox00000001.discobox.internal\n",
		"    HostName ssh.example.com\n",
		"    User sbx_devbox00000001\n",
		"    IdentitiesOnly yes\n",
		"    UserKnownHostsFile " + knownHostsPath + "\n",
	} {
		if !strings.Contains(config, want) {
			t.Fatalf("managed config missing %q:\n%s", want, config)
		}
	}
	// Written files are rewritten wholesale, so say so where someone will see it.
	if !strings.HasPrefix(config, "# Generated by") {
		t.Fatalf("managed config has no generated-file header:\n%s", config)
	}

	if got := readFile(t, knownHostsPath); got != "[ssh.example.com]:3222 ssh-ed25519 AAAAfakehostkey==\n" {
		t.Fatalf("known_hosts = %q", got)
	}

	userConfig := readFile(t, filepath.Join(home, ".ssh", "config"))
	if userConfig != "Include "+configPath+"\n" {
		t.Fatalf("user ssh config = %q", userConfig)
	}
	if !strings.Contains(stderr, configPath) {
		t.Fatalf("stderr should report what was written, got %q", stderr)
	}
}

// TestSSHConfigWriteIsIdempotent: this is a command people re-run whenever they
// create a sandbox, so it must not accumulate Include lines.
func TestSSHConfigWriteIsIdempotent(t *testing.T) {
	home, state, _ := runSSHConfigWrite(t, writeFakeServer())
	configPath, _ := managedPaths(state)
	userConfigPath := filepath.Join(home, ".ssh", "config")
	first := readFile(t, userConfigPath)

	// Re-run in the same HOME/state.
	server := writeFakeServer().start(t)
	cmd := NewRootCommand()
	cmd.SetOut(new(strings.Builder))
	var errOut strings.Builder
	cmd.SetErr(&errOut)
	cmd.SetArgs([]string{"--server", server.URL, "--project", "project-1", "box", "ssh-config", "--write"})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("second execute: %v", err)
	}

	if got := readFile(t, userConfigPath); got != first {
		t.Fatalf("second run changed ~/.ssh/config:\n%q\nwant\n%q", got, first)
	}
	if strings.Count(readFile(t, userConfigPath), "Include "+configPath) != 1 {
		t.Fatal("the Include line was duplicated")
	}
	if strings.Contains(errOut.String(), "added an Include") {
		t.Fatalf("second run claimed to add an Include again: %q", errOut.String())
	}
}

// TestSSHConfigWritePreservesAndPrecedesExistingConfig: ssh takes the first
// value obtained for each keyword, so an Include after a user's `Host *` block
// would lose every setting that block also sets.
func TestSSHConfigWritePreservesAndPrecedesExistingConfig(t *testing.T) {
	home := t.TempDir()
	state := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("XDG_STATE_HOME", state)
	if err := os.MkdirAll(filepath.Join(home, ".ssh"), 0o700); err != nil {
		t.Fatal(err)
	}
	existing := "Host *\n    IdentityFile ~/.ssh/id_rsa\n\nHost work\n    HostName work.example.com\n"
	userConfigPath := filepath.Join(home, ".ssh", "config")
	if err := os.WriteFile(userConfigPath, []byte(existing), 0o600); err != nil {
		t.Fatal(err)
	}

	server := writeFakeServer().start(t)
	cmd := NewRootCommand()
	cmd.SetOut(new(strings.Builder))
	cmd.SetErr(new(strings.Builder))
	cmd.SetArgs([]string{"--server", server.URL, "--project", "project-1", "box", "ssh-config", "--write"})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("execute ssh-config --write: %v", err)
	}

	got := readFile(t, userConfigPath)
	if !strings.HasPrefix(got, "Include ") {
		t.Fatalf("the Include must come first, got:\n%s", got)
	}
	if !strings.Contains(got, existing) {
		t.Fatalf("the user's existing config was not preserved verbatim:\n%s", got)
	}
}

func TestHasSSHConfigInclude(t *testing.T) {
	const managed = "/home/u/.local/state/discobox/cli/ssh/config"
	for _, tc := range []struct {
		name   string
		config string
		want   bool
	}{
		{name: "plain", config: "Include " + managed + "\n", want: true},
		{name: "indented and mixed case", config: "  include " + managed + "\n", want: true},
		{name: "quoted", config: `Include "` + managed + `"` + "\n", want: true},
		{name: "among several paths", config: "Include ~/.ssh/other " + managed + "\n", want: true},
		{name: "commented out does not count", config: "# Include " + managed + "\n", want: false},
		{name: "a different path", config: "Include ~/.ssh/other\n", want: false},
		{name: "empty", config: "", want: false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			if got := hasSSHConfigInclude(tc.config, managed); got != tc.want {
				t.Fatalf("hasSSHConfigInclude(%q) = %v, want %v", tc.config, got, tc.want)
			}
		})
	}
}
