// Code generated by go generate; DO NOT EDIT.

// Package model exposes stable aliases for generated worker-agent API schema types.
package model

import workeragentapi "github.com/obot-platform/discobox/worker-agent/api/gen"

type ErrorDetail = workeragentapi.ErrorDetail
type ErrorModel = workeragentapi.ErrorModel
type GitSource = workeragentapi.GitSource
type GitSourceCheckout = workeragentapi.GitSourceCheckout
type GitSourceDestination = workeragentapi.GitSourceDestination
type GitSourceWorkspace = workeragentapi.GitSourceWorkspace
type HarnessConfigFile = workeragentapi.HarnessConfigFile
type ResolvedHarnessConfig = workeragentapi.ResolvedHarnessConfig
type SandboxConfig = workeragentapi.SandboxConfig
type SandboxUpdateConfig = workeragentapi.SandboxUpdateConfig
type SandboxUser = workeragentapi.SandboxUser
type WorkerSandboxCreateRequest = workeragentapi.WorkerSandboxCreateRequest
type WorkerSandboxInstance = workeragentapi.WorkerSandboxInstance
type WorkerSandboxListResponse = workeragentapi.WorkerSandboxListResponse
type WorkerSandboxOperationRequest = workeragentapi.WorkerSandboxOperationRequest
type WorkerSandboxPort = workeragentapi.WorkerSandboxPort
type WorkerSandboxResources = workeragentapi.WorkerSandboxResources
type WorkerSandboxRuntime = workeragentapi.WorkerSandboxRuntime
type WorkerSandboxUpdateRequest = workeragentapi.WorkerSandboxUpdateRequest
