// Code generated by go generate; DO NOT EDIT.

// Package model exposes stable aliases for generated worker-agent API schema types.
package model

import workeragentapi "github.com/obot-platform/discobox/worker-agent/api/gen"

type AssignedPort = workeragentapi.AssignedPort
type ErrorDetail = workeragentapi.ErrorDetail
type ErrorModel = workeragentapi.ErrorModel
type GitSource = workeragentapi.GitSource
type GitSourceCheckout = workeragentapi.GitSourceCheckout
type GitSourceDestination = workeragentapi.GitSourceDestination
type GitSourceWorkspace = workeragentapi.GitSourceWorkspace
type ResourceConfig = workeragentapi.ResourceConfig
type Sandbox = workeragentapi.Sandbox
type WorkerSandboxCreateRequest = workeragentapi.WorkerSandboxCreateRequest
type WorkerSandboxListResponse = workeragentapi.WorkerSandboxListResponse
type WorkerSandboxOperationRequest = workeragentapi.WorkerSandboxOperationRequest
type WorkerSandboxUpdateRequest = workeragentapi.WorkerSandboxUpdateRequest
