// Code generated by ogen, DO NOT EDIT.

package apiclientgen

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateAgentConfigOperation             OperationName = "CreateAgentConfig"
	CreateSandboxOperation                 OperationName = "CreateSandbox"
	CreateSandboxProviderInstanceOperation OperationName = "CreateSandboxProviderInstance"
	DeleteAgentConfigOperation             OperationName = "DeleteAgentConfig"
	DeleteSandboxOperation                 OperationName = "DeleteSandbox"
	DeleteSandboxProviderInstanceOperation OperationName = "DeleteSandboxProviderInstance"
	GetAgentConfigOperation                OperationName = "GetAgentConfig"
	GetAgentConfigDefinitionOperation      OperationName = "GetAgentConfigDefinition"
	GetJobOperation                        OperationName = "GetJob"
	GetProjectOperation                    OperationName = "GetProject"
	GetSandboxOperation                    OperationName = "GetSandbox"
	GetSandboxProviderInstanceOperation    OperationName = "GetSandboxProviderInstance"
	ListAgentConfigDefinitionsOperation    OperationName = "ListAgentConfigDefinitions"
	ListAgentConfigsOperation              OperationName = "ListAgentConfigs"
	ListJobsOperation                      OperationName = "ListJobs"
	ListProjectsOperation                  OperationName = "ListProjects"
	ListSandboxProviderCatalogOperation    OperationName = "ListSandboxProviderCatalog"
	ListSandboxProviderInstancesOperation  OperationName = "ListSandboxProviderInstances"
	ListSandboxesOperation                 OperationName = "ListSandboxes"
	RegisterWorkerOperation                OperationName = "RegisterWorker"
	RestartSandboxOperation                OperationName = "RestartSandbox"
	StartSandboxOperation                  OperationName = "StartSandbox"
	StopSandboxOperation                   OperationName = "StopSandbox"
	UpdateAgentConfigOperation             OperationName = "UpdateAgentConfig"
	UpdateSandboxOperation                 OperationName = "UpdateSandbox"
	UpdateSandboxProviderInstanceOperation OperationName = "UpdateSandboxProviderInstance"
	UpdateWorkerStatusOperation            OperationName = "UpdateWorkerStatus"
)
