package main

import (
	"bufio"
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	openAPIPath := flag.String("openapi", "", "OpenAPI file containing components.schemas")
	schemasPath := flag.String("schemas", "", "generated oas_schemas_gen.go file")
	outPath := flag.String("out", "", "output Go file")
	genImport := flag.String("gen-import", "", "generated package import path")
	genPackage := flag.String("gen-package", "workeragentapi", "generated package import name")
	packageDoc := flag.String("package-doc", "Package model exposes stable aliases for generated worker-agent API schema types.", "generated package doc")
	flag.Parse()
	if *openAPIPath == "" || *schemasPath == "" || *outPath == "" || *genImport == "" {
		fatalf("openapi, schemas, out, and gen-import are required")
	}
	names, err := componentNames(*openAPIPath)
	if err != nil {
		fatalf("%v", err)
	}
	generated, err := generatedTypeNames(*schemasPath)
	if err != nil {
		fatalf("%v", err)
	}
	var buf bytes.Buffer
	fmt.Fprintln(&buf, "// Code generated by go generate; DO NOT EDIT.")
	fmt.Fprintln(&buf)
	fmt.Fprintf(&buf, "// %s\n", *packageDoc)
	fmt.Fprintln(&buf, "package model")
	fmt.Fprintln(&buf)
	fmt.Fprintf(&buf, "import %s %q\n", *genPackage, *genImport)
	fmt.Fprintln(&buf)
	for _, name := range names {
		if _, ok := generated[name]; !ok {
			continue
		}
		fmt.Fprintf(&buf, "type %s = %s.%s\n", name, *genPackage, name)
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fatalf("format generated aliases: %v", err)
	}
	if err := os.MkdirAll(filepath.Dir(*outPath), 0o755); err != nil {
		fatalf("create output directory: %v", err)
	}
	if err := os.WriteFile(*outPath, formatted, 0o644); err != nil {
		fatalf("write output: %v", err)
	}
}

func componentNames(path string) ([]string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	if strings.HasSuffix(path, ".json") {
		return jsonComponentNames(data)
	}
	return yamlComponentNames(data), nil
}

func jsonComponentNames(data []byte) ([]string, error) {
	var spec struct {
		Components struct {
			Schemas map[string]json.RawMessage `json:"schemas"`
		} `json:"components"`
	}
	if err := json.Unmarshal(data, &spec); err != nil {
		return nil, fmt.Errorf("parse OpenAPI JSON: %w", err)
	}
	names := make([]string, 0, len(spec.Components.Schemas))
	for name := range spec.Components.Schemas {
		names = append(names, name)
	}
	sort.Strings(names)
	return names, nil
}

func yamlComponentNames(data []byte) []string {
	scanner := bufio.NewScanner(bytes.NewReader(data))
	inComponents := false
	inSchemas := false
	names := []string{}
	for scanner.Scan() {
		line := scanner.Text()
		trimmed := strings.TrimSpace(line)
		switch {
		case trimmed == "components:" && leadingSpaces(line) == 0:
			inComponents = true
			inSchemas = false
			continue
		case inComponents && trimmed == "schemas:":
			inSchemas = true
			continue
		case inComponents && leadingSpaces(line) == 0 && trimmed != "" && trimmed != "components:":
			inComponents = false
			inSchemas = false
		}
		if !inSchemas {
			continue
		}
		if leadingSpaces(line) != 8 {
			continue
		}
		name, ok := strings.CutSuffix(trimmed, ":")
		if ok && name != "" {
			names = append(names, name)
		}
	}
	sort.Strings(names)
	return names
}

func leadingSpaces(line string) int {
	return len(line) - len(strings.TrimLeft(line, " "))
}

func generatedTypeNames(path string) (map[string]struct{}, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	names := map[string]struct{}{}
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if !strings.HasPrefix(line, "type ") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) >= 2 {
			names[fields[1]] = struct{}{}
		}
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("scan %s: %w", path, err)
	}
	return names, nil
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
