// Code generated by go generate; DO NOT EDIT.

// Package model exposes stable aliases for generated Server REST API schema types.
package model

import apigen "github.com/obot-platform/discobox/api/gen"

type AgentConfig = apigen.AgentConfig
type AgentConfigDefinition = apigen.AgentConfigDefinition
type AgentHookLog = apigen.AgentHookLog
type AgentHookLogsResponse = apigen.AgentHookLogsResponse
type AgentTerminal = apigen.AgentTerminal
type AgentTerminalEvent = apigen.AgentTerminalEvent
type AgentTerminalEventsResponse = apigen.AgentTerminalEventsResponse
type AgentTerminalLogEntry = apigen.AgentTerminalLogEntry
type AgentTerminalLogsResponse = apigen.AgentTerminalLogsResponse
type AgentTerminalsResponse = apigen.AgentTerminalsResponse
type CreateAgentConfigBody = apigen.CreateAgentConfigBody
type CreateAgentTerminalRequest = apigen.CreateAgentTerminalRequest
type CreateAgentTerminalResponse = apigen.CreateAgentTerminalResponse
type CreateSandboxBody = apigen.CreateSandboxBody
type CreateSandboxExecRequest = apigen.CreateSandboxExecRequest
type CreateSandboxExecResponse = apigen.CreateSandboxExecResponse
type CreateSandboxProviderInstanceBody = apigen.CreateSandboxProviderInstanceBody
type ErrorDetail = apigen.ErrorDetail
type ErrorModel = apigen.ErrorModel
type ErrorResponse = apigen.ErrorResponse
type GitSource = apigen.GitSource
type GitSourceCheckout = apigen.GitSourceCheckout
type GitSourceDestination = apigen.GitSourceDestination
type GitSourceWorkspace = apigen.GitSourceWorkspace
type Job = apigen.Job
type ListAgentConfigDefinitionsBody = apigen.ListAgentConfigDefinitionsBody
type ListAgentConfigsBody = apigen.ListAgentConfigsBody
type ListJobsBody = apigen.ListJobsBody
type ListProjectsBody = apigen.ListProjectsBody
type ListSandboxProviderCatalogBody = apigen.ListSandboxProviderCatalogBody
type ListSandboxProviderInstancesBody = apigen.ListSandboxProviderInstancesBody
type ListSandboxesBody = apigen.ListSandboxesBody
type ListWorkersBody = apigen.ListWorkersBody
type Project = apigen.Project
type ProjectMember = apigen.ProjectMember
type ProviderConfigField = apigen.ProviderConfigField
type ProviderStatus = apigen.ProviderStatus
type ProviderWorkerStatus = apigen.ProviderWorkerStatus
type RegisterWorkerBody = apigen.RegisterWorkerBody
type RegisterWorkerResponseBody = apigen.RegisterWorkerResponseBody
type ResourceHistoryResponse = apigen.ResourceHistoryResponse
type ResourceSnapshot = apigen.ResourceSnapshot
type RestartSandboxBody = apigen.RestartSandboxBody
type Sandbox = apigen.Sandbox
type SandboxConfig = apigen.SandboxConfig
type SandboxCreateConfig = apigen.SandboxCreateConfig
type SandboxExec = apigen.SandboxExec
type SandboxExecLogEntry = apigen.SandboxExecLogEntry
type SandboxExecLogsResponse = apigen.SandboxExecLogsResponse
type SandboxExecsResponse = apigen.SandboxExecsResponse
type SandboxProviderCatalogItem = apigen.SandboxProviderCatalogItem
type SandboxProviderInstance = apigen.SandboxProviderInstance
type SandboxProviderInstanceStatus = apigen.SandboxProviderInstanceStatus
type SandboxRuntime = apigen.SandboxRuntime
type SandboxUpdateConfig = apigen.SandboxUpdateConfig
type SandboxUser = apigen.SandboxUser
type StartSandboxBody = apigen.StartSandboxBody
type StopSandboxBody = apigen.StopSandboxBody
type UpdateAgentConfigBody = apigen.UpdateAgentConfigBody
type UpdateSandboxBody = apigen.UpdateSandboxBody
type UpdateSandboxProviderInstanceBody = apigen.UpdateSandboxProviderInstanceBody
type UpdateWorkerStatusBody = apigen.UpdateWorkerStatusBody
type User = apigen.User
type Worker = apigen.Worker
