// Code generated by go generate; DO NOT EDIT.

package model

const SandboxManifestAPIVersion = "discobox.dev/sandbox/v1"

// SandboxManifest Public, non-secret sandbox manifest read by the sandbox-agent from /etc/discobox/sandbox.json.
type SandboxManifest struct {
	// AgentRuntime Sandbox-agent local runtime settings. These values must not contain credentials, tokens, private keys, or other secret material.
	AgentRuntime *SandboxManifestAgentRuntime `json:"agentRuntime,omitempty"`
	// APIVersion Sandbox manifest contract version.
	APIVersion string `json:"apiVersion"`
	// Config Public sandbox configuration intent.
	Config SandboxConfig `json:"config"`
	// Provider Non-secret provider context for the sandbox runtime.
	Provider *SandboxManifestProvider `json:"provider,omitempty"`
	// ResolvedHarnessConfig Non-secret resolved default harness configuration, when one has been selected.
	ResolvedHarnessConfig *SandboxManifestResolvedHarnessConfig `json:"resolvedHarnessConfig,omitempty"`
	// Resources Provider-normalized resource allocation for the sandbox.
	Resources *SandboxResources `json:"resources,omitempty"`
	// SandboxID Stable sandbox ID.
	SandboxID string `json:"sandboxId"`
}

// SandboxManifestAgentRuntime Sandbox-agent daemon-local runtime settings. This object must not contain credentials, tokens, private keys, or other secret material.
type SandboxManifestAgentRuntime struct {
	// DatabasePath Sandbox-local SQLite database path.
	DatabasePath string `json:"databasePath,omitempty"`
	// ListenAddress Sandbox-agent HTTP listen address.
	ListenAddress string `json:"listenAddress,omitempty"`
	// ResourceCollection Sandbox-agent resource sampling settings.
	ResourceCollection *SandboxManifestResourceCollection `json:"resourceCollection,omitempty"`
	// RuntimeDir Sandbox-local runtime state directory.
	RuntimeDir string `json:"runtimeDir,omitempty"`
	// WorkingRoot Default working root inside the sandbox.
	WorkingRoot string `json:"workingRoot,omitempty"`
}

// SandboxManifestProvider Non-secret provider context. Secret material such as bearer tokens, bootstrap tokens, credentials, and private keys must be injected through a separate provider-owned channel, never through /etc/discobox/sandbox.json.
type SandboxManifestProvider struct {
	// Endpoints Non-secret provider endpoint hints keyed by provider-defined name.
	Endpoints map[string]string `json:"endpoints,omitempty"`
	// Kind Provider kind that produced the sandbox.
	Kind string `json:"kind"`
	// Metadata Non-secret provider-specific metadata keyed by provider-defined name.
	Metadata map[string]string `json:"metadata,omitempty"`
	// ProjectID Project ID when known to the provider.
	ProjectID string `json:"projectId,omitempty"`
	// PublicKeys Public verification keys keyed by provider-defined name. This map must contain public keys only.
	PublicKeys map[string]string `json:"publicKeys,omitempty"`
	// WorkerID Worker ID when the sandbox is hosted by a worker-backed provider.
	WorkerID string `json:"workerId,omitempty"`
}

// SandboxManifestResolvedHarnessConfig Non-secret resolved harness configuration selected for a sandbox.
type SandboxManifestResolvedHarnessConfig struct {
	// Files Files to write into the harness's home directory when the harness is installed. This content must not contain credentials, tokens, private keys, or other secret material.
	Files []HarnessConfigFile `json:"files,omitempty"`
	// ID Stable harness config ID.
	ID string `json:"id"`
	// Name Harness config display name.
	Name string `json:"name"`
}

// SandboxManifestResourceCollection Sandbox-agent resource collection settings.
type SandboxManifestResourceCollection struct {
	// RetentionCount Number of resource samples retained per runtime resource.
	RetentionCount int64 `json:"retentionCount,omitempty"`
	// SampleInterval Resource sampling interval as a Go-style duration string, for example 1s.
	SampleInterval string `json:"sampleInterval,omitempty"`
}

// SandboxResources Provider-normalized sandbox resource allocation.
type SandboxResources struct {
	// CPUCores Allocated CPU cores.
	CPUCores float64 `json:"cpuCores"`
	// DiskMB Allocated disk capacity in MiB.
	DiskMB int64 `json:"diskMb"`
	// MemoryMB Allocated memory in MiB.
	MemoryMB int64 `json:"memoryMb"`
	// TimeoutSeconds Provider runtime timeout in seconds. Zero means no provider-enforced timeout.
	TimeoutSeconds int64 `json:"timeoutSeconds"`
}
