#!/bin/sh
# Write a Homebrew formula for a released discobox tag.
#
# Usage: scripts/brew-formula.sh [--dev] <tag> [repo] [output]
#
# Two formulae come out of here, from the same assets and the same rules:
#
#   discobox      the stable channel, installed as `discobox`
#   discobox-dev  the latest channel (--dev), installed as `discobox-dev`
#
# They are separate formulae rather than one with a version switch because
# Homebrew refuses to link two formulae that install the same file, and the
# point of the dev channel is being able to hold both at once. So the dev
# formula installs its command under its own name; the CLI reads that name off
# argv[0] and calls itself by it.
#
# Generated rather than hand-edited because the checksums have to be of the
# assets the release actually uploaded — a formula with a stale sha256 fails for
# every user at once. The assets are downloaded and hashed here for that reason:
# what a user gets is what is verified, not a local rebuild of it.
#
# Run by `task brew:formula` and by the tap's own update workflow, which is why
# it is a script rather than a Taskfile heredoc: the tap updates itself from
# this repository's public releases and needs no credential to do it, so it
# cannot reach into a Taskfile that assumes a Go toolchain.
set -eu

dev=""
case "${1:-}" in
  --dev) dev=yes; shift ;;
esac

tag="${1:-}"
repo="${2:-discobox-ai/discobox}"

case "$tag" in
  v*) ;;
  *) echo "brew-formula: expected a v* tag, got '${tag}'" >&2; exit 1 ;;
esac
version="${tag#v}"

# Everything that differs between the two channels, decided once.
if [ -n "$dev" ]; then
  class=DiscoboxDev
  cmdname=discobox-dev
  desc="Sandboxed development environments for coding agents (latest channel)"
  default_out=build/discobox-dev.rb
else
  class=Discobox
  cmdname=discobox
  desc="Sandboxed development environments for coding agents"
  default_out=build/discobox.rb
fi
out="${3:-$default_out}"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

for asset in discobox-darwin-arm64 discobox-linux-amd64 discobox-linux-arm64; do
  gh release download "$tag" --repo "$repo" --pattern "$asset" --dir "$work"
done

sha() { sha256sum "$work/$1" | cut -d' ' -f1; }

# The paragraph about holding both channels at once, which only the dev formula
# has anything to say about. Written here so the caveats heredoc below stays one
# block for both.
both=""
if [ -n "$dev" ]; then
  both='      This is the latest channel: it tracks the newest tagged release, which
      has not been marked stable. Install it beside "discobox" and run it as
      "discobox-dev".

      Both share one state directory, one configuration, and one server stage,
      so their servers cannot run at the same time — that is deliberate, and
      whichever you start second will say so. Stop one before starting the
      other.

'
fi

mkdir -p "$(dirname "$out")"
cat > "$out" <<FORMULA
# Generated by scripts/brew-formula.sh in $repo. Do not edit by hand.
class $class < Formula
  desc "$desc"
  homepage "https://github.com/$repo"
  version "$version"
  license "Apache-2.0"

  on_macos do
    # Apple Silicon only. ADR 0062 defers Intel Macs and assemble-guest-image
    # refuses non-arm64, so an Intel binary would install and then fail at the
    # first pool.
    on_arm do
      url "https://github.com/$repo/releases/download/$tag/discobox-darwin-arm64"
      sha256 "$(sha discobox-darwin-arm64)"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/$repo/releases/download/$tag/discobox-linux-amd64"
      sha256 "$(sha discobox-linux-amd64)"
    end
    on_arm do
      url "https://github.com/$repo/releases/download/$tag/discobox-linux-arm64"
      sha256 "$(sha discobox-linux-arm64)"
    end
  end

  def install
    bin.install Dir["discobox-*"].first => "$cmdname"
  end

  def caveats
    <<~EOS
$both      This installs the client. The Discobox server is a separate program,
      downloaded on demand the first time something needs one locally and kept
      under your state directory by version. It is checked against the SHA-256
      this release was cut with, which is carried inside this binary; run
      "$cmdname admin server stage" to fetch it in advance, or
      "$cmdname admin server manifest" to see exactly what it would fetch.
    EOS
  end

  test do
    # Proves both that the binary runs on the platform it was installed for —
    # what a cross-compiled release most plausibly gets wrong — and that it is
    # the version this formula claims.
    assert_match version.to_s, shell_output("#{bin}/$cmdname --version")
  end
end
FORMULA
echo "wrote $out for $tag"
