#!/bin/sh
# Write the winget manifests for a released discobox tag.
#
# Usage: scripts/winget-manifests.sh <tag> [repo] [outdir]
#
# Generated rather than hand-edited for the reason scripts/brew-formula.sh is:
# the checksum has to be of the asset the release actually uploaded, so the
# archive is downloaded and hashed here. What a user installs is what was
# verified, not a local rebuild of it.
#
# A script rather than a Taskfile heredoc for the same reason as well: nothing
# here needs a Go toolchain, so this stays runnable by anything that can reach
# the repository's public releases.
set -eu

tag="${1:-}"
repo="${2:-discobox-ai/discobox}"
out="${3:-build/winget}"

case "$tag" in
  v*) ;;
  *) echo "winget-manifests: expected a v* tag, got '${tag}'" >&2; exit 1 ;;
esac

# The `v` comes off, and must never go back on. winget sorts versions
# semantically where it can and as strings otherwise, and the two orders
# disagree — so a package that publishes both forms ends up pinned to whichever
# version wins the wrong comparison. That is what happened to gptscript, whose
# only remedy was deleting the odd version out of the community repository
# (microsoft/winget-pkgs#140785). This also keeps one version string across
# both channels: the Homebrew formula already publishes `${tag#v}`.
version="${tag#v}"

identifier=Discobox.Discobox
# The path inside every archive, and the command the user ends up with. Both are
# discobox.exe by construction — see `release:windows-zip`.
nested=discobox.exe

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

gh release download "$tag" --repo "$repo" --pattern 'discobox-windows-*.zip' --dir "$work"

# One entry per archive the release uploaded, rather than a list of
# architectures here: an architecture added to the build matrix reaches winget
# by being built, and one dropped stops being offered without an edit.
installers=""
for archive in "$work"/discobox-windows-*.zip; do
  asset="$(basename "$archive")"
  goarch="${asset%.zip}"
  goarch="${goarch##*-}"
  # winget spells these differently from Go. Unknown rather than guessed: a new
  # GOARCH must be named here deliberately, because an installer offered under
  # the wrong architecture is one winget hands to the wrong machines.
  case "$goarch" in
    amd64) arch=x64 ;;
    arm64) arch=arm64 ;;
    *) echo "winget-manifests: no winget architecture known for $goarch ($asset)" >&2; exit 1 ;;
  esac

  # RelativeFilePath is resolved inside the archive, and winget does not check
  # it until someone installs the package: a manifest naming a file the archive
  # does not contain publishes cleanly and then leaves that user with no
  # discobox command at all.
  if ! unzip -l "$archive" | grep -qE "(^| )${nested}\$"; then
    echo "winget-manifests: $asset does not contain $nested" >&2
    exit 1
  fi

  # Uppercase because every generator in the ecosystem emits it that way, and a
  # diff against a neighbouring package should be about the package.
  sha="$(sha256sum "$archive" | cut -d' ' -f1 | tr 'a-f' 'A-F')"

  installers="$installers- Architecture: $arch
  InstallerUrl: https://github.com/$repo/releases/download/$tag/$asset
  InstallerSha256: $sha
"
done

if [ -z "$installers" ]; then
  echo "winget-manifests: $tag uploaded no discobox-windows-*.zip" >&2
  exit 1
fi

# The date the release was published, which is what the community repository's
# tooling records for every other package.
released="$(gh release view "$tag" --repo "$repo" --json publishedAt -q .publishedAt | cut -c1-10)"

mkdir -p "$out"

cat > "$out/$identifier.yaml" <<VERSION
# Generated by scripts/winget-manifests.sh in $repo. Do not edit by hand.
# yaml-language-server: \$schema=https://aka.ms/winget-manifest.version.1.12.0.schema.json

PackageIdentifier: $identifier
PackageVersion: $version
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.12.0
VERSION

cat > "$out/$identifier.locale.en-US.yaml" <<LOCALE
# Generated by scripts/winget-manifests.sh in $repo. Do not edit by hand.
# yaml-language-server: \$schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: $identifier
PackageVersion: $version
PackageLocale: en-US
Publisher: Discobox AI
PublisherUrl: https://github.com/discobox-ai
PublisherSupportUrl: https://github.com/$repo/issues
PackageName: Discobox
PackageUrl: https://github.com/$repo
License: Apache-2.0
LicenseUrl: https://github.com/$repo/blob/main/LICENSE
ShortDescription: Sandboxed development environments for coding agents
Description: |-
  Discobox runs coding agents in disposable, network-isolated boxes on your own
  machine, where the agent has a complete computer - root, package installs,
  whatever it wants - and none of your credentials. Everything inside the box
  is unconstrained. Everything that crosses the boundary goes through one door
  you control.
Moniker: discobox
Tags:
- agent
- ai
- cli
- coding-agent
- containers
- developer-tools
- sandbox
ReleaseNotesUrl: https://github.com/$repo/releases/tag/$tag
ManifestType: defaultLocale
ManifestVersion: 1.12.0
LOCALE

# Portable rather than an installer, and safe as one only because the Windows
# binary is built CGO_ENABLED=0: wherever winget can create a symlink it runs a
# portable package through its links directory, and a program that needs
# sibling DLLs cannot reach them from there (microsoft/winget-pkgs#133503).
# discobox ships one self-contained file and has none.
#
# ReleaseDate is quoted because the schema types it as a string, and an
# unquoted YYYY-MM-DD is a date to any parser that resolves timestamps.
cat > "$out/$identifier.installer.yaml" <<INSTALLER
# Generated by scripts/winget-manifests.sh in $repo. Do not edit by hand.
# yaml-language-server: \$schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: $identifier
PackageVersion: $version
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: $nested
  PortableCommandAlias: discobox
Commands:
- discobox
MinimumOSVersion: 10.0.0.0
ReleaseDate: "$released"
Installers:
${installers}ManifestType: installer
ManifestVersion: 1.12.0
INSTALLER

echo "wrote $identifier $version manifests to $out"
