// Code generated by ogen, DO NOT EDIT.

package serverapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateAgentConfig implements create-agent-config operation.
//
// Create an agent config.
//
// POST /projects/{projectId}/agent-configs
func (UnimplementedHandler) CreateAgentConfig(ctx context.Context, req *CreateAgentConfigBody, params CreateAgentConfigParams) (r CreateAgentConfigRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSandbox implements create-sandbox operation.
//
// Create a sandbox.
//
// POST /projects/{projectId}/sandboxes
func (UnimplementedHandler) CreateSandbox(ctx context.Context, req *CreateSandboxBody, params CreateSandboxParams) (r CreateSandboxRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSandboxProviderInstance implements create-sandbox-provider-instance operation.
//
// Create a sandbox provider instance.
//
// POST /projects/{projectId}/providers
func (UnimplementedHandler) CreateSandboxProviderInstance(ctx context.Context, req *CreateSandboxProviderInstanceBody, params CreateSandboxProviderInstanceParams) (r CreateSandboxProviderInstanceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteAgentConfig implements delete-agent-config operation.
//
// Delete an agent config.
//
// DELETE /projects/{projectId}/agent-configs/{agentConfigId}
func (UnimplementedHandler) DeleteAgentConfig(ctx context.Context, params DeleteAgentConfigParams) (r DeleteAgentConfigRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteSandbox implements delete-sandbox operation.
//
// Delete a sandbox.
//
// DELETE /projects/{projectId}/sandboxes/{sandboxId}
func (UnimplementedHandler) DeleteSandbox(ctx context.Context, params DeleteSandboxParams) (r DeleteSandboxRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteSandboxProviderInstance implements delete-sandbox-provider-instance operation.
//
// Delete a sandbox provider instance.
//
// DELETE /projects/{projectId}/providers/{providerId}
func (UnimplementedHandler) DeleteSandboxProviderInstance(ctx context.Context, params DeleteSandboxProviderInstanceParams) (r DeleteSandboxProviderInstanceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ForceJob implements force-job operation.
//
// Force a pending or backoff job to run immediately.
//
// POST /projects/{projectId}/jobs/{jobId}/force
func (UnimplementedHandler) ForceJob(ctx context.Context, params ForceJobParams) (r ForceJobRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAgentConfig implements get-agent-config operation.
//
// Get an agent config.
//
// GET /projects/{projectId}/agent-configs/{agentConfigId}
func (UnimplementedHandler) GetAgentConfig(ctx context.Context, params GetAgentConfigParams) (r GetAgentConfigRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAgentConfigDefinition implements get-agent-config-definition operation.
//
// Get an agent config definition.
//
// GET /agent-config-definitions/{definitionId}
func (UnimplementedHandler) GetAgentConfigDefinition(ctx context.Context, params GetAgentConfigDefinitionParams) (r GetAgentConfigDefinitionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetJob implements get-job operation.
//
// Get a job.
//
// GET /projects/{projectId}/jobs/{jobId}
func (UnimplementedHandler) GetJob(ctx context.Context, params GetJobParams) (r GetJobRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetProject implements get-project operation.
//
// Get a project.
//
// GET /projects/{projectId}
func (UnimplementedHandler) GetProject(ctx context.Context, params GetProjectParams) (r GetProjectRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSandbox implements get-sandbox operation.
//
// Get a sandbox.
//
// GET /projects/{projectId}/sandboxes/{sandboxId}
func (UnimplementedHandler) GetSandbox(ctx context.Context, params GetSandboxParams) (r GetSandboxRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSandboxProviderInstance implements get-sandbox-provider-instance operation.
//
// Get a sandbox provider instance.
//
// GET /projects/{projectId}/providers/{providerId}
func (UnimplementedHandler) GetSandboxProviderInstance(ctx context.Context, params GetSandboxProviderInstanceParams) (r GetSandboxProviderInstanceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListAgentConfigDefinitions implements list-agent-config-definitions operation.
//
// List agent config definitions.
//
// GET /agent-config-definitions
func (UnimplementedHandler) ListAgentConfigDefinitions(ctx context.Context) (r ListAgentConfigDefinitionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListAgentConfigs implements list-agent-configs operation.
//
// List agent configs.
//
// GET /projects/{projectId}/agent-configs
func (UnimplementedHandler) ListAgentConfigs(ctx context.Context, params ListAgentConfigsParams) (r ListAgentConfigsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListJobs implements list-jobs operation.
//
// List jobs for a project.
//
// GET /projects/{projectId}/jobs
func (UnimplementedHandler) ListJobs(ctx context.Context, params ListJobsParams) (r ListJobsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListProjects implements list-projects operation.
//
// List projects.
//
// GET /projects
func (UnimplementedHandler) ListProjects(ctx context.Context) (r ListProjectsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListSandboxProviderCatalog implements list-sandbox-provider-catalog operation.
//
// List sandbox provider catalog.
//
// GET /providers/catalog
func (UnimplementedHandler) ListSandboxProviderCatalog(ctx context.Context) (r ListSandboxProviderCatalogRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListSandboxProviderInstances implements list-sandbox-provider-instances operation.
//
// List sandbox provider instances.
//
// GET /projects/{projectId}/providers
func (UnimplementedHandler) ListSandboxProviderInstances(ctx context.Context, params ListSandboxProviderInstancesParams) (r ListSandboxProviderInstancesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListSandboxes implements list-sandboxes operation.
//
// List sandboxes.
//
// GET /projects/{projectId}/sandboxes
func (UnimplementedHandler) ListSandboxes(ctx context.Context, params ListSandboxesParams) (r ListSandboxesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListWorkers implements list-workers operation.
//
// List workers.
//
// GET /projects/{projectId}/workers
func (UnimplementedHandler) ListWorkers(ctx context.Context, params ListWorkersParams) (r ListWorkersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RegisterWorker implements register-worker operation.
//
// Register a bootstrapped worker.
//
// POST /api/workers/register
func (UnimplementedHandler) RegisterWorker(ctx context.Context, req *RegisterWorkerBody) (r RegisterWorkerRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RestartSandbox implements restart-sandbox operation.
//
// Restart a sandbox.
//
// POST /projects/{projectId}/sandboxes/{sandboxId}/restart
func (UnimplementedHandler) RestartSandbox(ctx context.Context, req *RestartSandboxBody, params RestartSandboxParams) (r RestartSandboxRes, _ error) {
	return r, ht.ErrNotImplemented
}

// StartSandbox implements start-sandbox operation.
//
// Start a sandbox.
//
// POST /projects/{projectId}/sandboxes/{sandboxId}/start
func (UnimplementedHandler) StartSandbox(ctx context.Context, req *StartSandboxBody, params StartSandboxParams) (r StartSandboxRes, _ error) {
	return r, ht.ErrNotImplemented
}

// StopSandbox implements stop-sandbox operation.
//
// Stop a sandbox.
//
// POST /projects/{projectId}/sandboxes/{sandboxId}/stop
func (UnimplementedHandler) StopSandbox(ctx context.Context, req *StopSandboxBody, params StopSandboxParams) (r StopSandboxRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateAgentConfig implements update-agent-config operation.
//
// Update an agent config.
//
// PATCH /projects/{projectId}/agent-configs/{agentConfigId}
func (UnimplementedHandler) UpdateAgentConfig(ctx context.Context, req *UpdateAgentConfigBody, params UpdateAgentConfigParams) (r UpdateAgentConfigRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateSandbox implements update-sandbox operation.
//
// Update a sandbox.
//
// PATCH /projects/{projectId}/sandboxes/{sandboxId}
func (UnimplementedHandler) UpdateSandbox(ctx context.Context, req *UpdateSandboxBody, params UpdateSandboxParams) (r UpdateSandboxRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateSandboxProviderInstance implements update-sandbox-provider-instance operation.
//
// Update a sandbox provider instance.
//
// PATCH /projects/{projectId}/providers/{providerId}
func (UnimplementedHandler) UpdateSandboxProviderInstance(ctx context.Context, req *UpdateSandboxProviderInstanceBody, params UpdateSandboxProviderInstanceParams) (r UpdateSandboxProviderInstanceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateWorkerStatus implements update-worker-status operation.
//
// Update worker status.
//
// POST /api/workers/{workerId}/status
func (UnimplementedHandler) UpdateWorkerStatus(ctx context.Context, req *UpdateWorkerStatusBody, params UpdateWorkerStatusParams) (r UpdateWorkerStatusRes, _ error) {
	return r, ht.ErrNotImplemented
}
