// Code generated by go generate; DO NOT EDIT.

// Package model exposes stable aliases for generated pool-agent API schema types.
package model

import poolagentapi "github.com/obot-platform/discobox/pool-agent/api/gen"

type ErrorDetail = poolagentapi.ErrorDetail
type ErrorModel = poolagentapi.ErrorModel
type GitSource = poolagentapi.GitSource
type GitSourceCheckout = poolagentapi.GitSourceCheckout
type GitSourceDestination = poolagentapi.GitSourceDestination
type GitSourceWorkspace = poolagentapi.GitSourceWorkspace
type HarnessConfigFile = poolagentapi.HarnessConfigFile
type HarnessSecret = poolagentapi.HarnessSecret
type HarnessVolume = poolagentapi.HarnessVolume
type PoolSandboxCreateRequest = poolagentapi.PoolSandboxCreateRequest
type PoolSandboxInstance = poolagentapi.PoolSandboxInstance
type PoolSandboxListResponse = poolagentapi.PoolSandboxListResponse
type PoolSandboxOperationAccepted = poolagentapi.PoolSandboxOperationAccepted
type PoolSandboxOperationRequest = poolagentapi.PoolSandboxOperationRequest
type PoolSandboxPort = poolagentapi.PoolSandboxPort
type PoolSandboxRuntime = poolagentapi.PoolSandboxRuntime
type PoolSandboxUpdateRequest = poolagentapi.PoolSandboxUpdateRequest
type PoolSyncRequest = poolagentapi.PoolSyncRequest
type ResolvedHarnessConfig = poolagentapi.ResolvedHarnessConfig
type SandboxConfig = poolagentapi.SandboxConfig
type SandboxGitIdentity = poolagentapi.SandboxGitIdentity
type SandboxUpdateConfig = poolagentapi.SandboxUpdateConfig
type SandboxUser = poolagentapi.SandboxUser
