package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

const sandboxAgentMarker = "x-sandbox-agent"

func main() {
	if err := run(); err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "gensandboxopenapi: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	sourcePath := "api/openapi/server.yaml"
	targetPath := "api/openapi/sandbox.yaml"
	source, err := readYAML(sourcePath)
	if err != nil {
		return err
	}
	paths, ok := asMap(source["paths"])
	if !ok {
		return fmt.Errorf("%s has no paths object", sourcePath)
	}

	outPaths := map[string]any{}
	for path, value := range paths {
		pathItem, ok := asMap(value)
		if !ok {
			continue
		}
		nextPathItem := map[string]any{}
		for _, method := range []string{"get", "put", "post", "delete", "patch", "options", "head", "trace"} {
			operation, ok := asMap(pathItem[method])
			if !ok || operation[sandboxAgentMarker] != true {
				continue
			}
			nextOperation := cloneMap(operation)
			delete(nextOperation, sandboxAgentMarker)
			nextPathItem[method] = nextOperation
		}
		if len(nextPathItem) > 0 {
			outPaths[path] = nextPathItem
		}
	}
	if len(outPaths) == 0 {
		return fmt.Errorf("%s has no operations marked %s: true", sourcePath, sandboxAgentMarker)
	}

	out := map[string]any{
		"openapi": source["openapi"],
		"info": map[string]any{
			"title":       "Discobox Sandbox Agent REST API",
			"version":     nestedString(source, "info", "version"),
			"description": "Generated subset of the canonical Discobox Server REST API implemented inside a sandbox.",
		},
		"servers": []any{
			map[string]any{
				"url":         "http://sandbox.local",
				"description": "Provider-delegated sandbox endpoint",
			},
		},
		"paths":      outPaths,
		"components": referencedComponents(source, outPaths),
	}
	data, err := yaml.Marshal(out)
	if err != nil {
		return err
	}
	var buf bytes.Buffer
	buf.WriteString("# Code generated by go generate ./api/internal/gensandboxopenapi; DO NOT EDIT.\n")
	buf.Write(data)
	if err := os.MkdirAll(filepath.Dir(targetPath), 0o755); err != nil {
		return err
	}
	return os.WriteFile(targetPath, buf.Bytes(), 0o600)
}

func readYAML(path string) (map[string]any, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var raw any
	if err := yaml.Unmarshal(data, &raw); err != nil {
		return nil, err
	}
	out, ok := normalizeYAML(raw).(map[string]any)
	if !ok {
		return nil, fmt.Errorf("%s did not decode to an object", path)
	}
	return out, nil
}

func normalizeYAML(value any) any {
	switch value := value.(type) {
	case map[string]any:
		out := make(map[string]any, len(value))
		for key, child := range value {
			out[key] = normalizeYAML(child)
		}
		return out
	case map[any]any:
		out := make(map[string]any, len(value))
		for key, child := range value {
			out[fmt.Sprint(key)] = normalizeYAML(child)
		}
		return out
	case []any:
		out := make([]any, len(value))
		for i, child := range value {
			out[i] = normalizeYAML(child)
		}
		return out
	default:
		return value
	}
}

func referencedComponents(source map[string]any, roots ...any) map[string]any {
	components, _ := asMap(source["components"])
	out := map[string]any{}
	needed := map[string]map[string]bool{}
	var scan func(any)
	scan = func(value any) {
		switch value := value.(type) {
		case map[string]any:
			if ref, ok := value["$ref"].(string); ok {
				category, name, ok := parseComponentRef(ref)
				if ok {
					if needed[category] == nil {
						needed[category] = map[string]bool{}
					}
					needed[category][name] = true
				}
			}
			for _, child := range value {
				scan(child)
			}
		case []any:
			for _, child := range value {
				scan(child)
			}
		}
	}
	for _, root := range roots {
		scan(root)
	}

	for {
		changed := false
		for _, category := range sortedKeys(needed) {
			sourceCategory, _ := asMap(components[category])
			if len(sourceCategory) == 0 {
				continue
			}
			outCategory, _ := asMap(out[category])
			if outCategory == nil {
				outCategory = map[string]any{}
				out[category] = outCategory
			}
			for _, name := range sortedBoolKeys(needed[category]) {
				if _, exists := outCategory[name]; exists {
					continue
				}
				component, exists := sourceCategory[name]
				if !exists {
					continue
				}
				outCategory[name] = component
				scan(component)
				changed = true
			}
		}
		if !changed {
			break
		}
	}
	return out
}

func parseComponentRef(ref string) (string, string, bool) {
	const prefix = "#/components/"
	if !strings.HasPrefix(ref, prefix) {
		return "", "", false
	}
	rest := strings.TrimPrefix(ref, prefix)
	category, name, ok := strings.Cut(rest, "/")
	return category, name, ok && category != "" && name != ""
}

func nestedString(root map[string]any, keys ...string) string {
	var current any = root
	for _, key := range keys {
		m, ok := asMap(current)
		if !ok {
			return ""
		}
		current = m[key]
	}
	value, _ := current.(string)
	return value
}

func asMap(value any) (map[string]any, bool) {
	m, ok := value.(map[string]any)
	return m, ok
}

func cloneMap(in map[string]any) map[string]any {
	out := make(map[string]any, len(in))
	for key, value := range in {
		out[key] = value
	}
	return out
}

func sortedKeys[M ~map[string]V, V any](m M) []string {
	keys := make([]string, 0, len(m))
	for key := range m {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func sortedBoolKeys(m map[string]bool) []string {
	keys := make([]string, 0, len(m))
	for key := range m {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}
